#pragma once
/* PlayMaker runtime port — internal interface of sim/fsm.  Every rule cites the decomp:
 *   PM  = analysis/decomp/PlayMaker/HutongGames.PlayMaker/
 *   PMF = analysis/decomp/PlayMaker/PlayMakerFSM.cs
 *   ACT = analysis/decomp/Assembly-CSharp/HutongGames.PlayMaker.Actions/
 *   HK  = analysis/decomp/Assembly-CSharp/
 * Static data: fsm_tables.h (generated by gen/gen_tables.py). */
#include <stdint.h>
#include <stdio.h>
#include <stdbool.h>
#include <stddef.h>
#include "fsm_tables.h"
#include "core/hksim.h"
#include "core/trap.h"
#include "core/rng.h"

typedef struct fsm_world fsm_world;
typedef struct scene_cache scene_cache;
typedef struct fsm_inst fsm_inst;
typedef struct act_inst act_inst;
typedef struct state_inst state_inst;

/* runtime variable slot; the bucket type decides which member is live (fsm_tables.h VB_*). */
typedef struct { float f; int32_t i; float v[4]; } fsm_val;

/* ---- actions ------------------------------------------------------------------------------------ */
typedef struct act_vtable {
    const char *type_short;                 /* "Wait" */
    size_t      state_size;                 /* per-instance private state (zeroed at creation) */
    void (*bind)(act_inst *a);              /* resolve field names -> pv pointers (once, at world load) */
    void (*on_enter)(act_inst *a);          /* PM/FsmStateAction.cs:201-223 virtuals */
    void (*on_update)(act_inst *a);
    void (*on_fixed_update)(act_inst *a);
    void (*on_late_update)(act_inst *a);
    void (*on_exit)(act_inst *a);
    bool (*on_event)(act_inst *a, int32_t ev); /* FsmStateAction.Event, base returns false (:176-179) */
    void (*proxy_cb)(act_inst *a, int kind, int32_t other_go, int32_t other_layer);   /* PlayMakerUnity2DProxy delegate (kind: 0 col enter,1 stay,2 exit,3 trig enter,4 stay,5 exit) */
} act_vtable;

struct act_inst {
    const fsm_action_def *def;
    const act_vtable *vt;                   /* NULL = type not ported -> HKSIM_UNIMPLEMENTED when it would run */
    fsm_inst *fsm;
    state_inst *state;
    int32_t index;                          /* index in the state's action array */
    uint64_t rng_site;
    const fsm_pv *arena; int32_t n_arena;         /* instance copy of the field values (+ referenced pool ranges) */
    int32_t n_fields;                       /* arena[0..n_fields) are the fields in declaration order */
    void *st;                               /* private state (vt->state_size) */
    uint8_t enabled, active, finished, entered;   /* FsmStateAction.cs:15,19,21,122 */
};

struct state_inst {
    const fsm_state_def *def;
    fsm_inst *fsm;
    act_inst *acts; int32_t n_acts;
    uint8_t active, finished;               /* FsmState.cs:10-16 */
    float state_time;
    int32_t loop_count, max_loop_count_seen;
    int32_t active_action_index;            /* FsmState.cs:53 */
    int32_t active_action;                  /* FsmState.activeAction (ExecutingAction) */
    int32_t *active_actions; int32_t n_active;      /* ordered, index-stable (FsmState.cs:58) */
    int32_t *finished_actions; int32_t n_finished;  /* FsmState.cs:62 */
};

typedef struct {                            /* PM/DelayedEvent.cs */
    int32_t id;                             /* stable identity (fsm_inst.next_delayed_id), NOT a slot index: the
                                              * live array is compacted and realloc'd.  0 is never issued, so a
                                              * zeroed action-state field means "no delayed event". */
    int32_t event;                          /* event string id */
    int32_t target;                         /* arena index of a PV_EVTARGET in the creating action, or -1 = Fsm.Event(ev) */
    act_inst *owner;                        /* action whose arena holds `target` */
    float timer, delay;
    uint8_t fired;
    /* captured Fsm.EventData (DelayedEvent.cs ctor :24-36): only the subset fsm_world tracks
     * (ev_sent_by_fsm/ev_int/ev_float/ev_string); the rest of FsmEventData is not modelled for any event. */
    int32_t sent_by_fsm;                    /* captured FsmEventData.SentByFsm (fsm id or -1) */
    int32_t ev_int; float ev_float; int32_t ev_string;
} delayed_ev;

struct fsm_inst {
    const fsm_def *def;
    int32_t id;
    fsm_world *w;
    int32_t go;
    state_inst *states; int32_t n_states;
    fsm_val *vals; int32_t n_vals;          /* flat variable store (fsm_def.var_start.. order) */
    fsm_val *dangling; int32_t *dangling_names; int32_t n_dangling, cap_dangling;  /* FsmVariables.cs:1195 fresh instances */
    int32_t active_state, previous_state, switch_to, last_transition;   /* Fsm.cs:107,138,141,144 */
    uint8_t started, finished, active_state_entered, switched_state;    /* Fsm.cs:354,558,795 */
    uint8_t component_enabled;              /* PlayMakerFSM (Behaviour.enabled); Fsm.cs:2386 sets it false */
    int32_t event_target;                   /* Fsm.EventTarget (SetEventTarget) — arena ref (-1 = null/self) */
    act_inst *event_target_owner;
    delayed_ev *delayed; int32_t n_delayed, cap_delayed;
    int32_t next_delayed_id;                /* delayed_ev.id source; pre-incremented so 0 is never issued */
    uint8_t in_fsm_list;                    /* PlayMakerFSM.fsmList membership */
    uint8_t handle_fixed, handle_late;      /* per-FSM opt-in flags read from the dump */
    uint8_t handle_2d;                      /* Fsm.HandleCollision{Enter,Stay,Exit}2D (bits 0-2) and HandleTrigger{Enter,Stay,Exit}2D
                                             * (bits 3-5): Fsm.CheckFsmEventsForEventHandlers (Fsm.cs:1685-1730) + Collision2dEvent
                                             * .OnPreprocess (ACT/Collision2dEvent.cs:40-55); computed in fsm_instantiate */
};

/* ---- scene objects ------------------------------------------------------------------------------ */
typedef struct {
    const col_def *def;
    uint8_t enabled, is_trigger;
    float offset[2], size[2], radius;
    uint32_t shape;                         /* phys_shape_id, 0 = not mirrored to phys */
    uint32_t body;                          /* core-owned static body carrying `shape` (rb_go < 0 only), 0 none */
    uint32_t prev_tick; float prev_rel[2];  /* HitboxObserver.prevRelCache (HO:54-55, 780-790) */
} col_inst;

typedef struct { act_inst **a; int32_t n, cap; } delegate_list;
/* The six PlayMakerUnity2DProxy delegate lists of one GameObject, allocated on first registration
 * (few objects ever register). */
typedef struct { delegate_list l[6]; } go_delegates;
/* HK/LimitSendEvents.cs state, allocated only for the objects on lse_gos. */
typedef struct { int32_t *sent; int32_t n, cap; int8_t prev; } go_lse;

typedef struct {
    const go_def *def;
    int32_t id;
    uint8_t active_self, active_in_hierarchy, destroyed;
    /* Dirty marks.  An object under a body (xf_covered) is also dirty whenever fsm_world.xf_epoch has moved on
     * since it was last clean (xf_clean / shape_clean): world_invalidate_body_transforms marks every such object
     * by advancing the epoch.  go_transform_dirty / go_shapes_dirty (gameobject.c) read both. */
    uint8_t transform_dirty;
    uint8_t shapes_dirty;   /* transform moved since the last physics-step shape flush (E-2 deferred flush) */
    uint8_t xf_tracked;     /* already on fsm_world.xf_gos */
    uint8_t xf_covered;     /* this object or an ancestor is on fsm_world.xf_gos (xf_refresh_cover) */
    uint32_t xf_clean, shape_clean;
    uint8_t has_static_body;   /* any col with rb_go < 0 bound to a core static body: ensure_transform_clean pushes to it */
    uint8_t rot_pending;       /* the last physics step turned the body: rot_pending_deg awaits the write-back */
    uint8_t rot_from_body;     /* the transform's rotation was just written from the body: record it, don't push it */
    float rot_pending_deg;
    int32_t parent, first_child, next_sibling;
    float local_pos[3], local_scale[3], local_euler_z;
    float world_pos[3], lossy_scale[3], world_euler_z;
    /* The inputs world_pos / world_euler_z / lossy_scale were last folded from (ensure_transform_clean): this level's
     * pose_in, and the parent's computation numbered pose_parent_gen.  pose_gen numbers this computation. */
    float pose_in[7]; uint32_t pose_gen, pose_parent_gen; uint8_t pose_ok;
    /* The local rotation as Unity stores it, a unit quaternion (x, y, z, w) (native-transform_time.md §1 T0):
     * localEulerAngles = (0, 0, local_euler_z) through EulerToQuaternion and SetLocalR (gameobject.c local_q),
     * recomputed when local_euler_z's bits change. */
    float local_q[4], local_q_src; uint8_t local_q_valid;
    uint8_t pos_pending;       /* the last physics step moved the body: its Transform awaits the write-back */
    float vel[2], gravity_scale; uint8_t kinematic, has_rb;
    uint32_t body;                          /* phys_body_id, 0 = none */
    /* Parent world pose (position, eulerZ, lossyScale) the body's pose was last synchronised against:
     * the pre-step flush carries a nested Rigidbody2D along when its parent moves. */
    float fol_ppos[2], fol_prot, fol_pscale[2]; uint8_t fol_valid;
    int32_t anim, hm, dh, recoil, constrain, arcy;   /* runtime component indices, -1 */
    uint8_t mesh_renderer_enabled;
    int32_t tag_override;                   /* GameObject.tag written at runtime by ACT/SetTag.cs:24; -1 = still def->tag.
                                             * GG_Grimm_Nightmare's Control flips its own tag 'Boss' <-> 'Spell Vulnerable'
                                             * in Inflate/Deflate and its Stun FSM reads it back with GetTag. */
    int16_t layer_override;                 /* GameObject.layer written at runtime (ACT/SetLayer.cs:29-35); -1 = still def->layer */
    uint32_t tink_ok_frame;                 /* TinkEffect.nextTinkTime as the first live frame allowed again (0 = never tinked) */
    uint8_t alert_in_range;                 /* AlertRange.isHeroInRange latch (HK/AlertRange.cs:7,17-27); false at load */
    uint8_t nonbouncer_active;              /* NonBouncer.active (NonBouncer.cs:5, initialises TRUE); SendMessage("SetActive", bool) writes it */
    /* ObjectPool membership (pool.c): the prefab (template root) whose pool this object belongs to, -1 none;
     * pool_spawned: in ObjectPool.spawnedObjects (spawned, not yet recycled) rather than in pooledObjects. */
    int32_t pool_of; uint8_t pool_spawned;
    int32_t mec;                            /* Animator instance (mecanim.c), -1 none */
    uint8_t fold_y180;                      /* a y half turn held as -z rotation over a mirrored x scale (SetRotation, transform.c) */
    go_delegates *dlg;                      /* PlayMakerUnity2DProxy delegates: 0 col enter,1 stay,2 exit,3 trig enter,4 stay,5 exit; NULL until one registers */
    col_inst *cols; int32_t n_cols;
    uint8_t has_transform;
    go_lse *lse;                            /* HK/LimitSendEvents.cs sentList + previousColliderState; NULL if no such component */
    /* HK/TrackTriggerObjects.cs, added at most once per GameObject by AddTrackTrigger (act_w1.c) and read by
     * CheckTrackTriggerCount.  tt_inside is insideGameObjects, de-duplicated like OnTriggerEnter2D's
     * `!Contains(gameObject)`; NULL until the first trigger enter.  The initial GetOverlappedColliders() scan
     * and the ignoreLayers mask are not modelled (no physics overlap query). */
    uint8_t tt_present;
    int32_t *tt_inside; int32_t n_tt_inside, cap_tt_inside;
} go_inst;

/* tk2dSpriteAnimator instance — HK/tk2dSpriteAnimator.cs */
typedef struct {
    const animator_def *def;
    int32_t go;
    int32_t lib;
    int32_t cur_clip;                       /* clip index or -1 */
    float clip_time, clip_fps;              /* :32-36 clipTime (frames), clipFps */
    int32_t previous_frame;                 /* :37 */
    int32_t sprite_id;                      /* tk2dBaseSprite._spriteId (:159): UpdateCollider runs only when it changes */
    int32_t sprite_def;                     /* SPRITEDEFS index of the last applied sprite (interned per (collection,
                                              * spriteId) pair by gen_tables.py) -- the real UpdateCollider change test
                                              * is on the (collection,id) PAIR, not the raw id alone; -1 = none
                                              * applied yet */
    uint8_t state;                          /* State flags: 1 Playing, 2 Paused (:7-12) */
    uint8_t enabled;
    uint8_t started, start_pending;         /* MonoBehaviour.Start ran / is due at the next Update pass (tk2dSpriteAnimator.cs:193-199, once per component) */
    /* animator.AnimationCompleted is a single C# delegate field: '=' assignment always overwrites the
     * previous owner, whoever it was (ACT/Tk2dPlayAnimationWithEvents.cs:59,63; HeroAnimationController.cs
     * :126,138,144,150,156; NailSlash.cs:98).  completed_kind says which of the three owner KINDS below is
     * live; only the matching fields are meaningful. */
    uint8_t completed_kind;                 /* 0 none/FSM (completed_owner), 1 HeroAnimationController, 2 NailSlash */
    act_inst *completed_owner; int32_t completed_event;   /* kind 0: an FSM action's own delegate (act_hk.c anim_set_completed_owner) */
    int32_t completed_slash_slot;           /* kind 2: which hero->slash[] this animator's NailSlash owns (core_iface.c hook_slash_anim) */
    act_inst *triggered_owner; int32_t triggered_event;
} anim_inst;

typedef struct {                            /* HK/HealthManager.cs */
    const hm_def *def; int32_t go;
    int32_t hp; uint8_t is_dead, invincible; int32_t invincible_from_direction;
    float evasion_by_hit_remaining;         /* :329 */
    int32_t direction_of_last_attack;
    int32_t stun_control_fsm;               /* fsm id, -1 */
    uint8_t death_event_sent;               /* HealthManager.SendDeathEvent fired OnDeath without setting isDead */
    uint8_t enemy_hit_did_fire_this_frame;  /* HK/EnemyHitEffectsUninfected.cs didFireThisFrame */
    int32_t obs_max_hp; uint8_t obs_seen;   /* HitboxObserver.ObserveMaxHp cache (HO:208-219) */
    uint8_t bound;                          /* in TrainingEnv._bossHMs yet?  Drives is_target AND damage credit. */
    uint8_t has_special_death, has_special_death_override;   /* SetSpecialDeath (HK/SetSpecialDeath.cs:26) mutates the runtime flag; hk_comp.c reads it over def-> */
    int32_t bound_max_hp;                   /* _bossMaxHPs[hm]: the hp AT BIND TIME, not the serialized pool */
} hm_inst;

typedef struct { const damagehero_def *def; int32_t go; int32_t damage_dealt; uint8_t enabled; } dh_inst;

typedef struct {                            /* HK/Recoil.cs */
    const recoil_def *def; int32_t go;
    float speed_base;                       /* recoilSpeedBase (SetRecoilSpeed writes it, :235-238) */
    uint8_t state;                          /* 0 Ready 1 Frozen 2 Recoiling (:11-16) */
    float time_remaining, speed;
    uint8_t is_sweeping; int32_t sweep_dir;
    float sweep_col_off[2], sweep_col_ext[2];
} recoil_inst;

/* AutoRecycleSelf instance -- HK/AutoRecycleSelf.cs.  Only afterEvent == TIME (0) has any runtime
 * behaviour to model; see world_autorecycle_update for the other three. */
typedef struct {
    const autorecycle_def *def; int32_t go;
    float timer;                            /* seconds since OnEnable armed the coroutine */
    uint8_t armed;                          /* the StartTimer coroutine is running */
} autorecycle_inst;

typedef struct { const constrain_def *def; int32_t go; } constrain_inst;

/* UnityEngine.Animator (mecanim.c): the one state's clock.  `playing`: the controller state exists (cleared by
 * deactivation, rebuilt at normalized time 0 by the next DirectorUpdateAnimationBegin); `nt` its normalized time;
 * `t` the clip time this frame's Begin sampled at; `evaluated`: Begin ran for it this frame. */
typedef struct { const mec_anim_def *def; int32_t go; uint8_t enabled, playing, evaluated; float nt, t; } mec_inst;

/* GrimmballControl — HK/GrimmballControl.cs.  GG_Grimm_Nightmare's `Flameball Grimmballoon`
 * (layer 12, CircleCollider2D + Rigidbody2D + DamageHero), the projectile of NKG's fire attack.
 *
 * Tracked in a world-side list rather than through a generated component def, because the component
 * is inert until ACT/FireGrimmBall.cs calls Fire() -- there is no state to reconstruct at scene
 * build time, and the ball outlives the FSM state that launched it (up to maxLifeTime seconds),
 * so it cannot live on the action instance either.
 *
 * `phase` mirrors the two coroutines: 1 = DoFire (AddForce every FixedUpdate), 2 = Shrink
 * (velocity *= 0.85 every Update, then Recycle).  0 = slot free. */
typedef struct {
    int32_t go;
    float force, tween_y;
    float max_life;          /* GrimmballControl.maxLifeTime; dumps/<scene>/hierarchy.json.gz records 10.0 */
    float elapsed;           /* DoFire  :   += Time.fixedDeltaTime until max_life  (GrimmballControl.cs:117-121) */
    float shrink;            /* Shrink  :   += Time.deltaTime until 0.5            (GrimmballControl.cs:130-135) */
    uint8_t phase;
} grimmball_inst;

/* ---- event log (mirrors oracle/Oracle/TraceRecorder.cs hooks; docs/trace-format.md EVENT 4/5) ---- */
enum { LOG_FSM_EVENT = 5, LOG_FSM_TRANSITION = 4, LOG_HERO_DAMAGE = 2, LOG_ENEMY_DAMAGE = 3,
       LOG_RNG = 100, LOG_NOTE = 101 };   /* kinds mirror docs/trace-format.md ev ids */
typedef struct { uint8_t kind; uint8_t phase; int32_t fsm; int32_t a, b, c; uint32_t frame; } log_rec;
/* log_rec.phase is the TRACE phase byte, not fsm_world.phase: the trace numbers the stages
 * 0 = Update/coroutine, 1 = FixedUpdate, 2 = LateUpdate, 3 = other/hook, while fsm_world.phase
 * numbers them in player-loop order (0 fixed, 1 update, 2 late).  world_log maps between them. */

/* PlayerData primitive store (dumps/<scene>/playerdata.json at SceneReady; sim/hero owns the live copy) */
typedef struct { int32_t name; uint8_t kind; float f; int32_t i; uint8_t b; int32_t s; float v[3]; } pd_val;

/* iTween (Assembly-CSharp/iTween.cs) runtime instance, see itween.c */
typedef struct {
    int32_t go;                             /* target GameObject */
    int32_t id;                             /* iTween.id (GenerateID :3751; a counter here) */
    int32_t events_id;                      /* iTweenFSMEvents.itweenID (iTweenFsmAction.cs:52-55) */
    act_inst *action;                       /* iTweenFsmAction reached through the events component; NULL once destroyed */
    uint8_t alive, started, running, physics, reverse, is_looping, donotfinish, use_real_time;
    uint8_t tick_pending;                   /* always 0: first tick timing is the lifecycle's (R2) */
    uint8_t restarted;                      /* iTween.loop, set by TweenRestart :2357 -- NOT loopType.  TweenStart
                                             * :2334-2338 skips ConflictCheck + GenerateTargets while it is set. */
    uint8_t has_speed;                      /* tweenArguments contains "speed": iTweenMoveBy.cs:108 / iTweenMoveTo.cs
                                             * add EITHER "time" OR "speed", and GenerateMove*Targets :1513-1517
                                             * overwrites time = distance / speed when the key is present. */
    float time, delay, running_time, percentage;
    float delay_elapsed;                    /* TweenDelay :2320-2329 (Start's initial WaitForSeconds(delay)),
                                              * accumulated dt by itween_run_update while the wait runs */
    float speed;
    float from[3], to[3];                   /* vector3s[0], vector3s[1] (GenerateScaleToTargets :1520-1556) */
    int32_t ease, loop;                     /* iTween.EaseType / LoopType enum values */
    int32_t start_event, finish_event;      /* iTweenFsmAction.startEvent / finishEvent (event ids, -1 = null) */
    uint8_t kind;                           /* 0 scale/to, 1 move/by, 2 move/to, 3 rotate/by, 4 rotate/to,
                                              * 5 shake/position, 6 color/to (FadeTo) */
    uint8_t method_by;                      /* kind==0 only: 1 if this is really a ScaleBy (method "by"), not a
                                              * ScaleTo (method "to") -- ConflictCheck-only distinction, itween.c */
    int32_t space;                          /* UnityEngine.Space for move (0 World, 1 Self) */
    float amount[3], last[3];               /* move/by: "amount" arg, vector3s[3] (last applied) */
    uint64_t shake_site;                    /* kind==5 only: RNG site for the per-frame Random.Range shake draws, captured
                                              * from the launching action at launch time (itween.c ApplyShakePositionTargets) */
} itween_inst;

/* act_core.c EventRegister: (GameObject, event name) pairs subscribed to a broadcast. */
#define FSM_EV_REG_CAP 1024
typedef struct { int32_t go; int32_t name; } ev_reg_entry;

struct fsm_world {
    const hkfsm_scene_def *sc;
    const struct scene_cache *cache;   /* arena template / rng sites / vtables, shared per scene */
    /* One calloc for every FSM structure whose size the scene table fixes: vals, state_inst[],
     * act_inst[], the action arena, the action-state block, and each GameObject's collider array.
     * blk_alloc hands out slices with a bump pointer, in world_create / fsm_instantiate order. */
    unsigned char *blk; size_t blk_size, blk_used;
    fsm_pv *arena;                     /* this world's copy of the template; act_inst.arena points in */
    unsigned char *act_st;             /* one zeroed block for every action's private state; act_inst.st points in */
    /* runtime string table: [0..sc->n_strings) static, then interned at runtime */
    char **dyn_strings; int32_t n_dyn, cap_dyn;
    int32_t *dyn_ix; uint32_t dyn_mask;     /* hash index over dyn_strings (events.c) */
    /* registered FsmEvent names: bitset over string ids (FsmEvent.cs eventLookup) */
    uint8_t *event_registered; int32_t cap_event_registered;
    /* The instance arrays below keep GROW_RESERVE (world.c) spare slots so a runtime Instantiate
     * (world_instantiate) appends without moving them: callers up the stack hold go_inst* / fsm_inst*.
     * world_reserve refills the spare only between stages, where nothing does. */
    go_inst *gos; int32_t n_gos, cap_gos;
    fsm_inst *fsms; int32_t n_fsms, cap_fsms;   /* one per scene fsm_def (same index) */
    int32_t *fsm_list; int32_t n_fsm_list, cap_fsm_list;   /* PlayMakerFSM.FsmList (enable order) */
    fsm_val *gvals; int32_t n_gvals;        /* PlayMakerGlobals variables */
    anim_inst *anims; int32_t n_anims, cap_anims;
    hm_inst *hms; int32_t n_hms;
    int32_t n_boss_hms;                     /* |derived boss set| (static membership) */
    int32_t n_bound_bosses;                 /* |_bossHMs| RIGHT NOW: 0 before a scan-route bind */
    int32_t agent_step;                     /* agent steps since reset, for the every-240-steps rescan */
    dh_inst *dhs; int32_t n_dhs, cap_dhs;
    recoil_inst *recoils; int32_t n_recoils, cap_recoils;
    autorecycle_inst *autorecycles; int32_t n_autorecycles, cap_autorecycles;   /* AutoRecycleSelf.StartTimer coroutines */
    constrain_inst *constrains; int32_t n_constrains, cap_constrains;
    /* Runtime Instantiate state (world.c world_instantiate): the per-world scene tables `sc` points at
     * once a clone exists, and the blocks the clones own.  NULL until the first clone. */
    struct world_grow *grow;
    grimmball_inst *grimmballs; int32_t n_grimmballs, cap_grimmballs;   /* GrimmballControl, armed by FireGrimmBall */
    mec_inst *mecs; int32_t n_mecs, cap_mecs;   /* Animator (Mecanim) components, one per mec_anim_def (mecanim.c) */
    itween_inst *itweens; int32_t n_itweens, cap_itweens;   /* runtime-added iTween components (creation order) */
    int32_t itween_id_count, itween_events_id_count;         /* iTween.GenerateID / iTweenFSMEvents.itweenIDCount */
    pd_val *pd; int32_t n_pd;
    /* FsmExecutionStack (PM/FsmExecutionStack.cs) */
    int32_t stack[256]; int32_t stack_depth;
    /* Fsm.EventData (static, Fsm.cs:31) */
    int32_t ev_sent_by_fsm; int32_t ev_int; float ev_float; int32_t ev_string;
    /* time */
    float dt, fixed_dt; uint32_t frame; float time;
    uint8_t phase;                          /* 0 FixedUpdate, 1 Update, 2 LateUpdate -- which player-loop
                                             * stage the world is executing (lifecycle.c trace_phase_of) */
    hk_rng *rng; hk_rng rng_own;            /* core-owned stream (sim_modules.h); rng_own for standalone worlds */
    /* physics */
    void *phys;
    /* log */
    log_rec *log; int32_t n_log, cap_log;
    int32_t dmg_src_go;      /* the DamageHero / damages_hero object currently being dispatched into HeroBox */
    bool log_enabled;
    /* misc */
    char err[512];
    bool is_boss_scene;                     /* BossSceneController.IsBossScene (HK/GGCheckIfBossScene.cs:16) */
    uint8_t bosses_dead_signal;             /* BossSceneController.OnBossesDead fired: EndBossScene() reached via the FSM action
                                             * EndGGBossScene or via CheckBossesDead (BossSceneController.cs:188-226).  This is the
                                             * game's own 'fight over' signal and the only one a special-death boss (NKG) ever raises. */
    uint8_t scene_left;                     /* a BeginSceneTransition ran (Dream Nail 'Leave Dream', dream return): the arena is gone */
    int32_t boss_level;                     /* BossSceneController.BossLevel: 0 Attuned, 1 Ascended, 2 Radiant (BossChallengeUI.cs:262-264 sets it
                                             * from the statue tier at scene setup).  From the table: the dump's meta.json bossLevel
                                             * (absent = 0).  Tier arenas are "<scene>@T1|@T2" tables
                                             * generated from analysis/dumps_t1|t2 (gen_tables.py split_level_key). */
    int32_t knight_go, camera_parent_go, game_manager_go;
    uint32_t   live_frame_seq;             /* frames run since reset */
    float      damage_landed_step;          /* TrainingEnv._damageLandedInStep: sum of DamageDealt/(n*maxHP)*100 */
    uint8_t hero_damage_pending;
    void *hero;                             /* struct hero (sim/hero/hero.h) bound by fsmi_create; NULL standalone */
    struct { int32_t name; fsm_val v; } *svars; int32_t n_svars;   /* StaticVariableList (HK) */
    uint8_t can_transition;                 /* BossSceneController.CanTransition (GGSetCanTransition) */
    uint32_t hero_body;                     /* phys body of the Knight (core-created), bound by world_bind_hero_body */
    int32_t *static_go; uint32_t n_static_go;  /* HKSIM_USER_STATIC_BASE + i -> owning GO, -1 unknown (world_bind_statics) */
    int32_t *lse_gos; int32_t n_lse_gos;    /* GameObjects carrying a LimitSendEvents (lifecycle.c LCT_LSE) */
    /* GameObjects that own a physics body or rigidbody: world_invalidate_body_transforms dirties their subtrees.
     * Append-only -- nothing ever clears go_inst.body or .has_rb. */
    int32_t *xf_gos; int32_t n_xf_gos, cap_xf_gos;
    /* go_inst.xf_covered as a bitset, kept up to date as the hierarchy and xf_gos change; recomputed in full at
     * the first use after the world is built (xf_cover_stale).  xf_epoch advances at every
     * world_invalidate_body_transforms. */
    uint32_t xf_epoch; uint8_t xf_cover_stale;
    uint32_t pose_gen;                      /* go_inst.pose_gen source */
    uint64_t *xf_cov_bits; int32_t n_cov_words;
    /* GameObjects whose shapes need rescaling before the next physics step.  Set by
     * invalidate_transform_dfs, drained by world_flush_dirty_shapes; go_inst.shapes_dirty
     * doubles as the already-set bit, so an object is rescaled at most once per flush.
     * A BITSET, drained in ascending GameObject order (the order the colliders are re-created in, and so
     * the order their new proxies take ids, port-phys.md#U2). */
    uint64_t *dirty_bits, *drain_bits; int32_t n_dirty_words;
    /* EventRegister subscribers (act_core.c): seeded from the scene table, appended to at runtime by
     * AddEventRegister.  FSM_EV_REG_CAP is act_core.c's trap bound. */
    ev_reg_entry ev_reg[FSM_EV_REG_CAP]; int32_t n_ev_reg;
    uint32_t obs_tick;                      /* HitboxObserver.MotionTick (HO:707) */
    void *obs_cache;                        /* observer.c per-collider cache */
    uint8_t hero_box_inactive;              /* HeroBox.inactive (hero hook hero_box_set_inactive) */
    uint32_t update_seq;
    struct lc_state *lc;                    /* the component lifecycle: registry, dispatch lists, Start queue,
                                             * coroutines, Destroy queue (lifecycle.c) */
    /* set only while fsm_enter_dumped_state restores an FSM's dumped state: suppresses fsm_event /
     * fsm_event_to / go_set_active / world_pool_spawn / Destroy (world.c) */
    uint8_t snapshot_mode;
    /* set only while the lockstep harness (sim/core/lockstep_api.c) re-enters the state the recorded game is in: the
     * recorded value of an action's private field, which act_live_float returns instead of the dump's */
    bool (*live_field)(void *ctx, const act_inst *a, const char *name, float *out); void *live_ctx;
};


/* An action that keeps an animator across frames keeps its index (+1, 0 = none), not a pointer: w->anims
 * moves when world_reserve grows it. */
static inline int32_t anim_ref(const fsm_world *w, const anim_inst *a) { return a ? (int32_t)(a - w->anims) + 1 : 0; }
static inline anim_inst *anim_deref(fsm_world *w, int32_t r) { return r ? &w->anims[r - 1] : NULL; }

/* UnityEngine.Mathf wrappers: Mathf.Atan2/Cos/Sin/Sqrt are (float)System.Math.X((double)f) — computed in
 * double and rounded once (cite: trace r2_rand1.a f25188 Control.$Angle = 22.948442 is the double-rounded
 * atan2 of the same operands; atan2f gives 22.948440).  Vector2.magnitude = (float)Math.Sqrt(x*x+y*y). */
#include <math.h>
static inline float m_atan2(float y, float x) { return (float)atan2((double)y, (double)x); }
static inline float m_cos(float x) { return (float)cos((double)x); }
static inline float m_sin(float x) { return (float)sin((double)x); }
static inline float m_sqrt(float x) { return (float)sqrt((double)x); }
static inline float m_pow(float x, float y) { return (float)pow((double)x, (double)y); }   /* Mathf.Pow, used by iTween's spring ease */

/* ---- strings / events ---- */
const char *w_str(const fsm_world *w, int32_t id);
int world_slash_index_of(fsm_world *w, int32_t go);   /* Knight/Attacks/<name> -> SLASH_* index, or -1 */
int32_t world_slash_go(fsm_world *w, int slash);      /* SLASH_* index -> Knight/Attacks/<name> GameObject, or -1 */
int32_t     w_intern(fsm_world *w, const char *s);
int32_t     w_find_string(const fsm_world *w, const char *s);            /* -1 if unknown */
int32_t     w_get_fsm_event(fsm_world *w, const char *name);            /* FsmEvent.GetFsmEvent(string): interns (FsmEvent.cs:402-413) */
int32_t     w_find_event(fsm_world *w, const char *name);               /* FsmEvent.FindEvent: -1 when never registered (:383-390) */
int32_t     w_get_fsm_event_id(fsm_world *w, int32_t name_id);
bool        w_event_registered(const fsm_world *w, int32_t name_id);

/* ---- variables / params ---- */
fsm_val *var_slot(fsm_inst *f, const fsm_pv *pv);                       /* NULL for literal/None */
float    pf(fsm_inst *f, const fsm_pv *pv);                             /* FsmFloat.Value read */
void     pf_set(fsm_inst *f, const fsm_pv *pv, float v);
int32_t  pi(fsm_inst *f, const fsm_pv *pv);                             /* FsmInt / FsmBool / FsmGameObject / FsmEnum .Value */
void     pi_set(fsm_inst *f, const fsm_pv *pv, int32_t v);
bool     pb(fsm_inst *f, const fsm_pv *pv);
void     pb_set(fsm_inst *f, const fsm_pv *pv, bool v);
int32_t  ps(fsm_inst *f, const fsm_pv *pv);                             /* FsmString.Value as string id */
void     ps_set(fsm_inst *f, const fsm_pv *pv, int32_t sid);
const float *pv3(fsm_inst *f, const fsm_pv *pv);                        /* FsmVector2/3/Quaternion/Color .Value */
void     pv3_set(fsm_inst *f, const fsm_pv *pv, const float *v);
int32_t  pgo(fsm_inst *f, const fsm_pv *pv);                            /* FsmGameObject.Value (go id / -1) */
void     pgo_set(fsm_inst *f, const fsm_pv *pv, int32_t go);
bool     p_isnone(const fsm_pv *pv);                                    /* NamedVariable.IsNone (:132-142) */
int32_t  p_event(const fsm_pv *pv);                                     /* FsmEvent field -> event string id or -1 (null) */
int32_t  p_owner_default(act_inst *a, const fsm_pv *pv);                /* Fsm.GetOwnerDefaultTarget (Fsm.cs:2458-2469) */
int32_t  p_get_safe(act_inst *a, const fsm_pv *pv);                     /* FsmOwnerDefault.GetSafe (HK/FSMUtility.cs:186-193) */
const fsm_pv  *a_field(act_inst *a, const char *name);                        /* field by name, NULL if absent */
const fsm_pv  *a_field_req(act_inst *a, const char *name);                    /* traps if absent */
const fsm_pv  *a_pv(act_inst *a, int32_t arena_index);
int32_t  a_array_len(act_inst *a, const fsm_pv *pv);
const fsm_pv  *a_array_elem(act_inst *a, const fsm_pv *pv, int32_t k);
int32_t  fsm_find_var(fsm_inst *f, int bucket, int32_t name_id);        /* FsmVariables.Find*: local only, -1 */
fsm_val *fsm_get_var(fsm_inst *f, int bucket, int32_t name_id, bool *fresh); /* FsmVariables.Get*: local, global, else fresh dangling */

/* ---- runtime (fsm_rt.c) ---- */
void state_silent_enter(fsm_inst *f, int32_t s);
float act_live_float(act_inst *a, const char *name, float dflt);   /* private action state at SceneReady, dump restore only */
void fsm_enter_dumped_state(fsm_world *w, fsm_inst *f);   /* start in active_state_at_dump (world_restore_scene) */
void state_silent_exit(fsm_inst *f, int32_t s);
void act_proxy_callback(act_inst *a, int kind, int32_t other_go, int32_t other_layer);
void world_restore_scene(fsm_world *w);
/* iTween (itween.c) */
int32_t itween_scale_to(fsm_world *w, int32_t go, const float scale[3], float time, float delay, int32_t ease, int32_t loop,
                        bool ignore_timescale, int32_t events_id, act_inst *action, bool donotfinish, bool is_looping,
                        int32_t start_event, int32_t finish_event);
void    itween_stop_type(fsm_world *w, int32_t go, const char *type);
void    itween_sever_events(fsm_world *w, int32_t events_id);
void world_animators_start(fsm_world *w);
void fsm_start(fsm_inst *f);                       /* Fsm.Start  Fsm.cs:1863-1893 */
void fsm_update(fsm_inst *f);                      /* Fsm.Update Fsm.cs:1895-1922 (+PlayMakerFSM.Update gate) */
void fsm_fixed_update(fsm_inst *f);                /* Fsm.FixedUpdate :1950-1958 */
void fsm_late_update(fsm_inst *f);                 /* Fsm.LateUpdate :1960-1968 */
void fsm_on_enable(fsm_inst *f);                   /* PlayMakerFSM.OnEnable :363-367 + Fsm.OnEnable :1839-1856 */
void fsm_on_disable(fsm_inst *f);                  /* PlayMakerFSM.OnDisable :392-403 */
void fsm_stop(fsm_inst *f);                        /* Fsm.Stop / StopAndReset :1970-2004 (ACT/FinishFSM.cs) */
void fsm_process_event(fsm_inst *f, int32_t ev, bool with_data, int32_t sent_by);   /* Fsm.ProcessEvent :2023-2080 */
void fsm_event(fsm_inst *f, int32_t ev);           /* Fsm.Event(FsmEvent) :2192-2198 (recorder hook point) */
void fsm_event_name(fsm_inst *f, const char *name);/* Fsm.Event(string) :2184-2190 */
void fsm_event_to(fsm_inst *f, act_inst *owner, int32_t target_arena, int32_t ev);  /* Fsm.Event(FsmEventTarget, FsmEvent) :2126-2182 */
void fsm_update_state_changes(fsm_inst *f);        /* :2314-2325 */
void fsm_switch_state(fsm_inst *f, int32_t to);    /* :2347-2365 */
void fsm_goto_previous_state(fsm_inst *f);         /* :2367-2373 */
bool fsm_is_active(const fsm_inst *f);             /* Fsm.Active :546-556 */
bool fsm_is_switching(const fsm_inst *f);          /* :560 */
void fsm_add_delayed(fsm_inst *f, act_inst *owner, int32_t target_arena, int32_t ev, float delay, int32_t *out_id);
bool delayed_was_sent(const fsm_inst *f, int32_t id);   /* DelayedEvent.WasSent (id 0 / not-live -> true) */
void act_finish(act_inst *a);                      /* FsmStateAction.Finish :181-189 */
int32_t fsm_owner_go(const fsm_inst *f);
int32_t exec_fsm(const fsm_world *w);              /* FsmExecutionStack.ExecutingFsm (-1 none) */
void push_fsm(fsm_world *w, int32_t id);
void pop_fsm(fsm_world *w);
const char *fsm_label(const fsm_inst *f);          /* "owner/fsm" for messages */
const char *state_name(const fsm_inst *f, int32_t s);

/* Unity-side entry points into an FSM (fsm_rt.c) */
void fsm_on_trigger2d(fsm_inst *f, int kind /*0 enter 1 stay 2 exit*/, int32_t other_go);   /* Fsm.OnTriggerEnter2D :2813-2829 etc. */
void fsm_on_collision2d(fsm_inst *f, int kind, int32_t other_go, int32_t other_layer);

/* ---- world (sim/fsm/runtime) ---- */
fsm_world *world_create(const hkfsm_scene_def *sc);
void       world_destroy(fsm_world *w);
void       world_log(fsm_world *w, uint8_t kind, int32_t fsm, int32_t a, int32_t b);
void       world_log4(fsm_world *w, uint8_t kind, int32_t fsm, int32_t a, int32_t b, int32_t c);
int32_t    world_go_find_path(const fsm_world *w, const char *path);
int32_t    world_go_find_name(const fsm_world *w, const char *name);   /* GameObject.Find (ASSUMPTION: first by dump order, Q-pfsm) */
int32_t    world_fsm_find(const fsm_world *w, int32_t go, const char *fsm_name);  /* first LIVE FSM on go with that name (component order) */
int32_t    world_fsm_locate(const fsm_world *w, int32_t go, const char *fsm_name); /* FSMUtility.LocateFSM: first with that name, live or not */
int32_t    world_fsm_first(const fsm_world *w, int32_t go);              /* go.GetComponent<PlayMakerFSM>() */
void       world_send_event_to_go(fsm_world *w, int32_t go, const char *ev, bool recursive);
int32_t    world_pool_spawn(fsm_world *w, int32_t prefab, const float pos[3], float euler_z);   /* ObjectPool.Spawn (pool.c) */
void       world_pool_recycle(fsm_world *w, int32_t go);                                     /* ObjectPool.Recycle (pool.c) */
int32_t    world_pool_count(const fsm_world *w, int32_t prefab);                             /* ObjectPool.GetPooled(prefab).Count */
void       world_pool_create_one(fsm_world *w, int32_t prefab);                              /* ObjectPool.CreatePool(prefab, 1) */
int32_t    world_instantiate_at(fsm_world *w, int32_t prefab, const float pos[3], float euler_z);   /* Object.Instantiate (pool.c) */
int32_t    world_pool_prefab(const fsm_world *w, const char *clone_name);                    /* a dumped pool family's prefab (pool.c) */
bool       world_prefab_matters(const fsm_world *w, int32_t prefab);                          /* a copy of it is observable (pool.c) */
int32_t    world_alert_range_find(fsm_world *w, int32_t root, const char *child_name);  /* AlertRange.Find :46-66 */
bool       world_alert_in_range(fsm_world *w, int32_t go);   /* AlertRange.cs:17-27 isHeroInRange */
void       tt_trigger_event(fsm_world *w, int32_t go, int32_t other, bool enter);   /* TrackTriggerObjects.OnTrigger*2D
                                                                                     * (go_inst.tt_present/tt_inside above; act_w1.c), dispatched from physics.c */
float      world_take_damage_landed(fsm_world *w);   /* reads and clears damage_landed_step */
void       world_broadcast_event(fsm_world *w, int32_t ev, int32_t from_fsm, bool exclude_self, bool with_data, int32_t sent_by);  /* Fsm.cs:2222-2232 */
void       world_broadcast_to_go(fsm_world *w, int32_t go, int32_t ev, bool send_to_children, bool exclude_self, int32_t from_fsm, int32_t sent_by); /* :2242-2270 */
void       world_send_to_fsm_on_go(fsm_world *w, int32_t go, int32_t fsm_name_sid, int32_t ev, int32_t from_fsm);  /* :2280-2307 */
void       go_set_active(fsm_world *w, int32_t go, bool active);         /* GameObject.SetActive -> OnEnable/OnDisable of PlayMakerFSMs (ENGINE ASSUMPTION: synchronous, Q-fsmact-4) */
bool       go_active_in_hierarchy(const fsm_world *w, int32_t go);
void       go_set_layer(fsm_world *w, int32_t go, int32_t layer);   /* GameObject.layer setter: moves the object's colliders to that layer-matrix row */
int32_t    go_find_child(const fsm_world *w, int32_t go, const char *name);   /* Transform.Find (path with '/') */
int32_t    go_parent(const fsm_world *w, int32_t go);
void       go_set_parent(fsm_world *w, int32_t go, int32_t parent);
void       go_world_pos(fsm_world *w, int32_t go, float out[3]);
void       go_set_world_pos(fsm_world *w, int32_t go, const float p[3]);
void       go_local_pos(fsm_world *w, int32_t go, float out[3]);
void       go_world_to_local_point(fsm_world *w, int32_t parent, const float p[3], float out[3]);   /* Transform.InverseTransformPoint under `parent` (-1 = world) */
void       go_set_local_pos(fsm_world *w, int32_t go, const float p[3]);
void       go_local_scale(const fsm_world *w, int32_t go, float out[3]);
void       go_set_local_scale(fsm_world *w, int32_t go, const float s[3]);
void       go_lossy_scale(const fsm_world *w, int32_t go, float out[3]);
float      go_euler_z(const fsm_world *w, int32_t go);
float      go_local_euler_z(const fsm_world *w, int32_t go);
void       go_transform_direction(fsm_world *w, int32_t go, const float d[2], float out[2]);   /* Transform.TransformDirection (xy) */
void       go_set_euler_z(fsm_world *w, int32_t go, float z);
void       world_push_body_rotations(fsm_world *w, int32_t go);
void       go_set_local_euler_z(fsm_world *w, int32_t go, float z);
void       world_xf_track(fsm_world *w, int32_t go);
void       world_invalidate_body_transforms(fsm_world *w);
bool       go_has_rb(const fsm_world *w, int32_t go);
void       go_velocity(fsm_world *w, int32_t go, float out[2]);
void       go_set_velocity(fsm_world *w, int32_t go, const float v[2]);
void       go_add_force(fsm_world *w, int32_t go, const float f[2]);   /* Rigidbody2D.AddForce, ForceMode2D.Force */
float      go_angular_velocity(fsm_world *w, int32_t go);              /* Rigidbody2D.angularVelocity, degrees/s */
void       go_set_angular_velocity(fsm_world *w, int32_t go, float deg_per_s);
void       go_add_torque(fsm_world *w, int32_t go, float torque, bool impulse);   /* Rigidbody2D.AddTorque, ForceMode2D Force / Impulse */
void       go_set_gravity_scale(fsm_world *w, int32_t go, float g);
void       go_set_kinematic(fsm_world *w, int32_t go, bool k);
void       go_set_simulated(fsm_world *w, int32_t go, bool on);        /* Rigidbody2D.simulated (ACT/SetRigidbodySimulated2D.cs) */
bool       go_has_component(const fsm_world *w, int32_t go, const char *type_short);
col_inst  *go_box_collider(fsm_world *w, int32_t go);                   /* GetComponent<BoxCollider2D>() (first) */
col_inst  *go_poly_collider(fsm_world *w, int32_t go);                  /* GetComponent<PolygonCollider2D>() (first) */
col_inst  *go_first_collider(fsm_world *w, int32_t go);                 /* GetComponent<Collider2D>() */
col_inst  *world_add_box_collider(fsm_world *w, int32_t go);            /* AddComponent<BoxCollider2D>() */
void       world_phys_add_collider(fsm_world *w, int32_t go, const col_inst *c);
void       col_bounds(fsm_world *w, int32_t go, const col_inst *c, float min[2], float max[2]);  /* Collider2D.bounds (world AABB) */
void       col_shape_bounds(fsm_world *w, int32_t go, const col_inst *c, float min[2], float max[2]);  /* the shape's AABB, enabled or not */
void       col_set_enabled(fsm_world *w, col_inst *c, bool on);
void       col_set_trigger(fsm_world *w, col_inst *c, bool on);
void       col_set_box(fsm_world *w, int32_t go, col_inst *c, const float *size, const float *offset);
const char *go_name(const fsm_world *w, int32_t go);
const char *go_path(const fsm_world *w, int32_t go);
int32_t    go_tag(const fsm_world *w, int32_t go);
int32_t    go_layer(const fsm_world *w, int32_t go);
void       proxy_add(fsm_world *w, int32_t go, int kind, act_inst *a);
void       proxy_remove(fsm_world *w, int32_t go, int kind, act_inst *a);
void       world_dispatch_trigger(fsm_world *w, int32_t go, int kind, int32_t other_go, int32_t other_layer);    /* PlayMakerUnity2DProxy.OnTrigger*2D (HK/PlayMakerUnity2DProxy.cs:190-241) */
void       world_dispatch_collision(fsm_world *w, int32_t go, int kind, int32_t other_go, int32_t other_layer);  /* :143-188 */
bool       world_raycast(fsm_world *w, const float origin[2], const float dir[2], float len, uint32_t layer_mask, bool *hit_is_trigger);
void       world_phys_bind(fsm_world *w);                          /* bodies/shapes of the FSM-owned Rigidbody2Ds in sim/phys */
void       world_slash_set_enabled(fsm_world *w, int slash, bool poly_on, bool tink_on);   /* NailSlash poly / Clash Tink colliders */
void       world_rebake_polygon_shapes(fsm_world *w, int32_t go);  /* after a transform-scale change */
void       world_flush_dirty_shapes(fsm_world *w);                 /* E-2 deferred flush: push moved child colliders into Box2D, once per physics step */
int32_t    world_array_elems(act_inst *a, const fsm_pv *pv, const fsm_pv **elems);   /* FsmArray (literal or variable) element pvs */
void       knight_slash_trigger(fsm_world *w, int slash, int other_layer, int nonbouncer_active, int is_bounce_shroom, int is_big_bouncer);
void       knight_box_check_for_damage(fsm_world *w, float other_pos_x, int damage_dealt, int hazard_type, int shadow_dash_hazard, int has_damages_hero_fsm);
struct obs_combat_src;
bool       world_has_active_enemy_hitbox(fsm_world *w);
uint32_t   world_combat_sources(fsm_world *w, struct obs_combat_src *out, const char **kinds, const char **keys, uint32_t cap, float knight_x, float knight_y);
uint32_t   world_fsm_snapshots(fsm_world *w, const char **out, uint32_t cap);
void       world_obs_cache_free(fsm_world *w);
int32_t    itween_scale_to(fsm_world *w, int32_t go, const float scale[3], float time, float delay, int32_t ease, int32_t loop,
                           bool ignore_timescale, int32_t events_id, act_inst *action, bool donotfinish, bool is_looping,
                           int32_t start_event, int32_t finish_event);
/* `has_speed` is the "speed" KEY being present, which is what GenerateMoveByTargets :1513 tests -- not
 * `speed != 0`.  The two differ: speed 0 with the key present gives time = +inf and a tween that never
 * moves and never completes, where a missing key leaves `time` alone. */
int32_t    itween_move_by(fsm_world *w, int32_t go, const float amount[3], int32_t space, float time, float delay,
                          float speed, bool has_speed, int32_t ease, int32_t loop,
                          bool ignore_timescale, int32_t events_id, act_inst *action, bool donotfinish, bool is_looping,
                          int32_t start_event, int32_t finish_event);
int32_t    itween_rotate_by(fsm_world *w, int32_t go, const float amount[3], int32_t space, float time, float delay, int32_t ease, int32_t loop,
                          bool ignore_timescale, int32_t events_id, act_inst *action, bool donotfinish, bool is_looping,
                          int32_t start_event, int32_t finish_event);
int32_t    itween_move_to(fsm_world *w, int32_t go, const float pos[3], int32_t space, float time, float delay, float speed,
                          int32_t ease, int32_t loop, bool ignore_timescale, int32_t events_id, act_inst *action,
                          bool donotfinish, bool is_looping, int32_t start_event, int32_t finish_event);
int32_t    itween_rotate_to(fsm_world *w, int32_t go, const float rot[3], int32_t space, float time, float delay, float speed,
                          int32_t ease, int32_t loop, bool ignore_timescale, int32_t events_id, act_inst *action,
                          bool donotfinish, bool is_looping, int32_t start_event, int32_t finish_event);
int32_t    itween_shake_position(fsm_world *w, int32_t go, const float amount[3], int32_t space, float time, float delay,
                          int32_t loop, bool ignore_timescale, int32_t events_id, act_inst *action, bool donotfinish,
                          bool is_looping, int32_t start_event, int32_t finish_event);
int32_t    itween_fade_to(fsm_world *w, int32_t go, float time, float delay, int32_t ease, int32_t loop,
                          bool ignore_timescale, int32_t events_id, act_inst *action, bool donotfinish, bool is_looping,
                          int32_t start_event, int32_t finish_event);
void       itween_stop_type(fsm_world *w, int32_t go, const char *type);
void       itween_sever_events(fsm_world *w, int32_t events_id);
float      itween_ease_value(int32_t ease_type, float start, float end, float value, const char *label);
void       world_phys_ensure_body(fsm_world *w, int32_t go);   /* deferred pooled Rigidbody2D */
void       world_bind_hero_body(fsm_world *w, uint32_t body);
void       world_bind_statics(fsm_world *w, const int32_t *instance_ids, const uint32_t *bodies, const uint32_t *shapes, uint32_t n);
void       world_phys_event(fsm_world *w, const void *phys_event_ptr);   /* const phys_event * (sim/core/phys.h) */
int32_t    world_go_of_user(fsm_world *w, uint32_t user);
bool       world_raycast_ex(fsm_world *w, const float origin[2], const float dir[2], float len, uint32_t layer_mask,
                            float hit_point[2], float hit_normal[2], int32_t *hit_go, bool *hit_is_trigger);
/* PlayerData (act_knight.c): the hero's store when bound, else the dump copy */
int32_t    world_pd_int(fsm_world *w, const char *name);
bool       world_pd_bool(fsm_world *w, const char *name);
float      world_pd_float(fsm_world *w, const char *name);
void       world_pd_vector3(fsm_world *w, const char *name, float out[3]);
int32_t    world_pd_string(fsm_world *w, const char *name);
void       world_pd_set_int(fsm_world *w, const char *name, int32_t v);
void       world_pd_set_bool(fsm_world *w, const char *name, bool v);
void       world_pd_set_float(fsm_world *w, const char *name, float v);
void       world_pd_set_string(fsm_world *w, const char *name, int32_t sid);
int32_t    random_weighted_index(act_inst *a, const fsm_pv *weights);   /* ActionHelpers.GetRandomWeightedIndex: ONE Range(0,sum) draw (act_core.c) */
void       world_boss_bind_tick(fsm_world *w);                     /* TrainingEnv's every-240-steps boss rescan */
int32_t    world_scan_bind_boss_hms(fsm_world *w);                 /* TrainingEnv.ScanBindBossHMs */
void       world_hero_soul_gain(fsm_world *w);                     /* HeroController.SoulGain via sim/hero */
void       world_hero_add_mp(fsm_world *w, int amount);             /* HeroController.AddMPCharge via sim/hero */
int32_t    world_global_go(fsm_world *w, const char *name);         /* FsmVariables.GlobalVariables.GetFsmGameObject(name).Value, -1 */
void       world_hero_recoil_left(fsm_world *w);                   /* HeroController.RecoilLeft via sim/hero (HealthManager.cs:363) */
void       world_hero_recoil_down(fsm_world *w);                   /* HeroController.RecoilDown via sim/hero (TinkEffect.cs:87) */
void       world_hero_recoil_right(fsm_world *w);                  /* HeroController.RecoilRight via sim/hero (HealthManager.cs:366) */
bool       knight_send_message(act_inst *a, int32_t target_go, const char *fn, const fsm_pv *func_call);   /* SendMessage dispatch (act_knight.c) */
bool       is_under(const fsm_world *w, int32_t go, int32_t root);
pd_val    *world_pd(fsm_world *w, const char *name);

/* ---- tk2d (tk2d.c) ---- */
anim_inst *anim_of_go(fsm_world *w, int32_t go);
void anim_play_name(fsm_world *w, anim_inst *a, const char *name);      /* tk2dSpriteAnimator.Play(string) :235-238 */
void anim_play_from_frame(fsm_world *w, anim_inst *a, int32_t frame);   /* PlayFromFrame(int) :245-252 */
void anim_play_from_frame_named(fsm_world *w, anim_inst *a, const char *name, int32_t frame);   /* PlayFromFrame(string,int) :253-262, ONE Warp */
void anim_stop(anim_inst *a);
void anim_play(fsm_world *w, anim_inst *a, int32_t clip, float clip_start_time, float override_fps);   /* Play(clip, clipStartTime, overrideFps) :291-340 */
void anim_play_default(fsm_world *w, anim_inst *a);
void anim_update(fsm_world *w, anim_inst *a, float dt);                 /* UpdateAnimation :433-526 */
bool anim_playing(const anim_inst *a);
void anim_set_paused(anim_inst *a, bool on);   /* tk2dSpriteAnimator.Pause/Resume :401-409 */
int32_t anim_current_frame(const fsm_world *w, const anim_inst *a);     /* CurrentFrame :146-183 */
float anim_clip_time_seconds(const fsm_world *w, const anim_inst *a);   /* :117-127 */
void  anim_restore_dumped(fsm_world *w, anim_inst *a);   /* dump -> animator state, no Play(), wrap-aware frame */
const char *anim_clip_name(const fsm_world *w, const anim_inst *a);
void anim_set_completed_owner(fsm_world *w, anim_inst *a, act_inst *owner, int32_t event);   /* animator.AnimationCompleted = <FSM action> (last writer wins), tk2d.c */

/* ---- HK components (hk_comp.c) ---- */
hm_inst *hm_of_go(fsm_world *w, int32_t go);
/* HitTaker.Hit (HitTaker.cs:6-22) as TakeDamage calls it: the IHitResponder of `target` and of up to two parents */
void world_hit_taker(fsm_world *w, int32_t target, int32_t source, int attack_type, int damage_dealt, float direction,
                     bool circle_direction, bool ignore_invulnerable, float magnitude, float multiplier);
void hm_update(fsm_world *w, hm_inst *h);                               /* HealthManager.Update :327-330 */
void hm_hit(fsm_world *w, hm_inst *h, int32_t source_go, int attack_type, int damage_dealt, float direction,
            bool circle_direction, bool ignore_invulnerable, float magnitude_multiplier, float multiplier);   /* HealthManager.Hit :332-347 */
void recoil_by_direction(fsm_world *w, recoil_inst *r, int dir, float magnitude);   /* Recoil.cs:112-152 */
void recoil_fixed_update(fsm_world *w, recoil_inst *r);                 /* :191-194 */
void world_autorecycle_arm(fsm_world *w, int32_t go);                   /* AutoRecycleSelf.OnEnable :19-42 */
void constrain_update(fsm_world *w, constrain_inst *c);                 /* ConstrainPosition.cs:17-51 */
/* GrimmballControl — HK/GrimmballControl.cs:96-99 Fire, :103-123 DoFire, :83-93 DoHit, :125-140 Shrink */
void grimmball_fire(fsm_world *w, int32_t go, float tween_y, float force);
void grimmball_do_hit(fsm_world *w, int32_t go);
int  cardinal_direction(float degrees);                                 /* DirectionUtils.cs:13-21 */

/* ---- action registry (act_core.c) ---- */
const act_vtable *act_lookup(const char *type_short);
int  act_registry_count(void);
const char *act_registry_name(int i);
const char *act_registry_owner(int i);   /* which act_<name>.c registered index i */
