"""Guards the trainer-facing contract in docs/sim-api.md against silent drift.

Everything else in tests/ measures whether the SIMULATION is right.  This one measures whether
the SURFACE is still what an integrator was told it is, so a refactor cannot quietly change the deal:
the exported symbol set, the ABI version, the scene list, the wire payload, and determinism.

Run: pytest tests/test_contract.py     (HKSIM_DLL selects the DLL)

If this fails, docs/sim-api.md is the file to update -- not this test.
"""
import ctypes, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))
sys.path.insert(0, ROOT)
from hkpy import obs_codec, sim_driver

DLL = os.environ.get("HKSIM_DLL") or os.path.join(ROOT, "sim", "build", "hksim.dll")

# docs/sim-api.md "One instance" / "Observation".  A symbol leaving this list is a breaking change for every integrator.
STABLE_SYMBOLS = ["hksim_abi_version", "hksim_create", "hksim_destroy", "hksim_reset", "hksim_step",
                  "hksim_obs", "hksim_last_error",
                  # the fast path (hksim.h "STABLE: the fast path")
                  "hksim_set_obs_mode", "hksim_obs_batch", "hksim_vocab_create", "hksim_vocab_destroy",
                  "hksim_vocab_size", "hksim_vocab_str", "hksim_vocab_intern"]
# Scenes every build must contain (docs/sim-api.md "Scenes"; the registry is generated by sim/gen_registries.py).
SCENES = ["GG_Hornet_1", "GG_Gruz_Mother", "GG_False_Knight", "GG_Mega_Moss_Charger"]
ABI = 1
HKSIM_ERR_UNKNOWN_LEVEL = 2


def _lib():
    lib = sim_driver.load(DLL)
    lib.hksim_obs.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    lib.hksim_obs.restype = ctypes.c_size_t
    return lib


def _obs(lib, sim):
    n = lib.hksim_obs(sim, None, 0)
    buf = ctypes.create_string_buffer(n)
    lib.hksim_obs(sim, buf, n)
    return buf.raw[:n]


def _episode(lib, level, seed, steps=40):
    """-> (list of obs payloads, list of step results) for a fixed action script."""
    cfg = sim_driver.Config(level.encode(), 2, seed, 0)
    sim = lib.hksim_create(ctypes.byref(cfg))
    assert sim, "create %s: %s" % (level, lib.hksim_last_error(None))
    try:
        assert lib.hksim_reset(sim, seed) == 0, lib.hksim_last_error(sim)
        payloads, results = [_obs(lib, sim)], []
        res = sim_driver.StepResult()
        for i in range(steps):
            act = (ctypes.c_int32 * 4)(i % 3, (i // 3) % 3, (i // 2) % 8, i % 2)
            rc = lib.hksim_step(sim, act, ctypes.byref(res))
            assert rc == 0, "%s step %d: %s" % (level, i, lib.hksim_last_error(sim).decode())
            payloads.append(_obs(lib, sim))
            results.append((res.done, res.damage_landed, res.hits_taken, res.hp_healed, res.frame))
            if res.done:
                break
        return payloads, results
    finally:
        lib.hksim_destroy(sim)


def test_abi_and_symbols():
    lib = ctypes.CDLL(DLL)
    missing = [s for s in STABLE_SYMBOLS if not hasattr(lib, s)]
    assert not missing, "DLL is missing stable symbols: %s" % missing
    lib.hksim_abi_version.restype = ctypes.c_uint32
    got = lib.hksim_abi_version()
    assert got == ABI, "ABI version %d, docs/sim-api.md says %d" % (got, ABI)


def test_scene_list():
    """Every scene the DLL advertises creates; an unknown one fails loudly rather than silently.

    The list comes from hksim_scene_count/name rather than a constant here, so a newly ported boss
    is covered automatically and a boss that silently dropped out of the build is caught.
    """
    lib = _lib()
    lib.hksim_scene_name.restype = ctypes.c_char_p
    advertised = [lib.hksim_scene_name(i).decode() for i in range(lib.hksim_scene_count())]
    assert lib.hksim_scene_name(len(advertised)) is None, "hksim_scene_name did not reject an out-of-range index"
    for level in SCENES:
        assert level in advertised, "documented scene %s is not in the build: %s" % (level, advertised)
    for level in advertised:
        cfg = sim_driver.Config(level.encode(), 2, 1, 0)
        sim = lib.hksim_create(ctypes.byref(cfg))
        assert sim, "documented scene %s failed to create: %s" % (level, lib.hksim_last_error(None))
        lib.hksim_destroy(sim)
    cfg = sim_driver.Config(b"GG_Not_A_Scene", 2, 1, 0)
    assert not lib.hksim_create(ctypes.byref(cfg)), "an unknown level created a world instead of failing"


def test_obs_decodes_as_the_wire():
    """hksim_obs must be decodable by the independent transcription of BinaryProtocol.cs Pack()."""
    lib = _lib()
    payloads, results = _episode(lib, "GG_Hornet_1", 4242, steps=20)
    reset, step = obs_codec.decode(payloads[0]), obs_codec.decode(payloads[1])
    assert reset["type"] == obs_codec.MSG_RESET and step["type"] == obs_codec.MSG_STEP
    assert step["gs"].shape == (obs_codec.GLOBAL_DIM,), step["gs"].shape
    assert step["combat"].shape[1] == obs_codec.COMBAT_FEAT
    assert step["terrain"].shape[1] == obs_codec.TERRAIN_FEAT
    for name in ("damage_landed", "hits_taken", "hp_healed", "done"):
        assert name in step, "step payload lost the %s reward scalar" % name
    assert len(results[0]) == 5, "hksim_step_result changed shape"


def test_determinism():
    """Seeded-only is the contract (docs/sim-api.md "Determinism and threads"): identical seed + actions => identical bytes."""
    lib = _lib()
    for level in SCENES:
        a, _ = _episode(lib, level, 99, steps=30)
        b, _ = _episode(lib, level, 99, steps=30)
        assert a == b, "%s is not reproducible from its seed" % level


def test_instances_are_independent():
    """docs/sim-api.md "Determinism and threads" concurrency claim: co-live instances must not perturb each other.

    sim/ holds process-global scratch (fsm/fsm_world.c:1647, fsm/act_core.c:673), so this is a real
    risk, not a formality.  Sequential round-robin only -- multi-THREADED stepping is not claimed.
    """
    lib = _lib()
    solo = [_episode(lib, lv, 7, steps=30)[0] for lv in SCENES]

    sims = []
    for lv in SCENES:
        cfg = sim_driver.Config(lv.encode(), 2, 7, 0)
        s = lib.hksim_create(ctypes.byref(cfg))
        assert s and lib.hksim_reset(s, 7) == 0
        sims.append(s)
    try:
        together = [[_obs(lib, s)] for s in sims]
        res = sim_driver.StepResult()
        for i in range(30):
            act = (ctypes.c_int32 * 4)(i % 3, (i // 3) % 3, (i // 2) % 8, i % 2)
            for k, s in enumerate(sims):
                if lib.hksim_step(s, act, ctypes.byref(res)) != 0:
                    raise AssertionError("%s step %d: %s" % (SCENES[k], i, lib.hksim_last_error(s).decode()))
                together[k].append(_obs(lib, s))
                if res.done:
                    together[k] = together[k][:len(solo[k])]
    finally:
        for s in sims:
            lib.hksim_destroy(s)
    for k, lv in enumerate(SCENES):
        n = min(len(solo[k]), len(together[k]))
        assert solo[k][:n] == together[k][:n], "%s diverges when stepped alongside siblings" % lv


def test_batch_matches_the_wire():
    """The fast path must be the wire path's numbers, exactly.

    This is the assertion that makes hksim_obs_batch safe to keep forever: the wire path is what the
    parity gate verifies against recorded game fights, so anything the fast path reports differently
    is a defect in the fast path, not a difference of opinion.  Run with both bits set so a single
    step produces both representations from the same obs_view.
    """
    import numpy as np
    lib = _lib()
    assert getattr(lib, "_hksim_batch_ok", False), "DLL has no fast path (rebuild)"
    vocab = lib.hksim_vocab_create(0)
    assert vocab, "hksim_vocab_create returned NULL"
    try:
        assert lib.hksim_vocab_str(vocab, 0) == b"unknown", "id 0 must be 'unknown' (vocab.py:23-24)"
        assert lib.hksim_vocab_str(vocab, 1) == b"terrain", "id 1 must be 'terrain' (vocab.py:23-24)"
        for level in SCENES:
            cfg = sim_driver.Config(level.encode(), 2, 1234, 0)
            sim = lib.hksim_create(ctypes.byref(cfg))
            assert sim, lib.hksim_last_error(None)
            try:
                lib.hksim_set_obs_mode(sim, sim_driver.HKSIM_OBS_WIRE | sim_driver.HKSIM_OBS_BATCH)
                assert lib.hksim_reset(sim, 1234) == 0, lib.hksim_last_error(sim)
                buf = sim_driver.BatchBuffers(1, cap_combat=64, cap_terrain=256)
                res = sim_driver.StepResult()
                for i in range(120):
                    act = (ctypes.c_int32 * 4)(i % 3, (i // 3) % 3, (i // 2) % 8, i % 2)
                    assert lib.hksim_step(sim, act, ctypes.byref(res)) == 0, lib.hksim_last_error(sim).decode()
                    wire = obs_codec.decode(_obs(lib, sim))
                    sim_driver.obs_batch(lib, [sim], vocab, buf)
                    where = "%s step %d" % (level, i)

                    nc, nt = int(buf["n_combat"][0]), int(buf["n_terrain"][0])
                    assert nc == wire["nc"], "%s: n_combat %d != wire %d" % (where, nc, wire["nc"])
                    assert nt == wire["nt"], "%s: n_terrain %d != wire %d" % (where, nt, wire["nt"])
                    assert np.array_equal(buf["combat"][0, :nc], wire["combat"]), "%s: combat rows differ" % where
                    assert np.array_equal(buf["terrain"][0, :nt], wire["terrain"]), "%s: terrain rows differ" % where
                    assert np.array_equal(buf["global_state"][0], wire["gs"]), "%s: global_state differs" % where
                    assert np.array_equal(
                        buf["step"][0],
                        np.array([wire["damage_landed"], wire["hits_taken"], wire["hp_healed"]], np.float32)),                         "%s: step scalars differ" % where
                    assert int(buf["done"][0]) == wire["done"], "%s: done differs" % where

                    # ids must decode back to the exact strings the wire carried (obs-wire.md 3.4/3.5),
                    # with "" and "unknown" both landing on 0 the way KindVocab does.
                    for k in range(nc):
                        for col, want in (("combat_kind", wire["kinds"][k]), ("combat_parent", wire["parents"][k])):
                            got = lib.hksim_vocab_str(vocab, int(buf[col][0, k]))
                            got = got.decode() if got else None
                            if want in ("", "unknown"):
                                assert int(buf[col][0, k]) == 0, "%s: %s %r should be id 0" % (where, col, want)
                            else:
                                assert got == want, "%s: %s id -> %r, wire said %r" % (where, col, got, want)
                    if res.done:
                        break
            finally:
                lib.hksim_destroy(sim)
    finally:
        lib.hksim_vocab_destroy(vocab)


def test_batch_rejects_misuse():
    """A caller that forgets hksim_set_obs_mode must get a named error, not silent zeros."""
    lib = _lib()
    cfg = sim_driver.Config(b"GG_Hornet_1", 2, 1, 0)
    sim = lib.hksim_create(ctypes.byref(cfg))
    assert sim and lib.hksim_reset(sim, 1) == 0
    vocab = lib.hksim_vocab_create(0)
    try:
        buf = sim_driver.BatchBuffers(1)
        try:
            sim_driver.obs_batch(lib, [sim], vocab, buf)
            raise AssertionError("batch call succeeded without HKSIM_OBS_BATCH")
        except RuntimeError as e:
            assert "HKSIM_OBS_BATCH" in str(e), "unhelpful error: %s" % e
    finally:
        lib.hksim_vocab_destroy(vocab); lib.hksim_destroy(sim)


TESTS = [test_abi_and_symbols, test_scene_list, test_obs_decodes_as_the_wire,
         test_determinism, test_instances_are_independent,
         test_batch_matches_the_wire, test_batch_rejects_misuse]

if __name__ == "__main__":
    if not os.path.exists(DLL):
        print("SKIP: no DLL at", DLL); sys.exit(2)
    bad = 0
    for t in TESTS:
        try:
            t(); print("  PASS %s" % t.__name__)
        except Exception as e:
            bad += 1; print("  FAIL %s -> %s" % (t.__name__, repr(e)[:300]))
    print("PASS test_contract" if not bad else "FAIL test_contract (%d/%d)" % (bad, len(TESTS)))
    sys.exit(1 if bad else 0)
