"""Generates sim/hero/hero_fields.h (X-macro lists) from the recorded trace header and the hero dump.

    python sim/hero/gen_fields.py

Sources: analysis/traces/p0/r2_move.a.hktrace header fields.hero / fields.cstate / fields.playerdata
(docs/trace-format.md #Header: every primitive HeroController field, declaration order) and
analysis/dumps/GG_Hornet_1/hero.json (System.Boolean vs Int32/enum so bools get a 'b' code).
The PlayerData subset is the set of keys HeroController reads or writes (grep over HeroController.cs
for GetBool/GetInt/SetIntSwappedArgs/SetBoolSwappedArgs + the PlayerData methods it calls).
"""
import json
import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, ROOT)
from hkpy.hktrace import read_trace  # noqa: E402

# PlayerData keys HeroController touches (grep HeroController.cs) + keys the PlayerData methods it calls
# touch (PlayerData.cs TakeHealthInternal:8582-8614, orig_AddHealth:8629-8643, MaxHealth:4630-4636,
# orig_UpdateBlueHealth:8616-8627, AddMPCharge:4779-4813, TakeMP:4815-4829, CurrentMaxHealth:3084-3094,
# SetHazardRespawn:5069-5080).
PD_KEYS = """
health maxHealth maxHealthBase healthBlue joniHealthBlue damagedBlue prevHealth blockerHits
MPCharge maxMP MPReserve MPReserveMax soulLimited focusMP_amount
disablePause isInvincible invinciTest infiniteAirJump overcharmed betaEnd permadeathMode
hasDash canDash hasWalljump canWallJump hasDoubleJump hasSuperDash hasShadowDash hasDreamNail hasNailArt
hasAcidArmour hasLantern canBackDash hasDreamGate atBench respawnType environmentType grimmChildLevel
hazardRespawnFacingRight brokenCharm_23 killedBlocker killsBlocker
""".split() + ["equippedCharm_%d" % i for i in range(1, 41)]


def main():
    t = read_trace(os.path.join(ROOT, "analysis", "traces", "p0", "r2_move.a.hktrace"))
    h = t.header["fields"]
    hero = json.load(open(os.path.join(ROOT, "analysis", "dumps", "GG_Hornet_1", "hero.json")))
    hc = {e["name"]: e for e in hero["heroController"]}
    pd_types = {e["name"]: e["type"] for e in h["playerdata"]}
    pdj = json.load(open(os.path.join(ROOT, "analysis", "dumps", "GG_Hornet_1", "playerdata.json")))
    pd_clr = {e["name"]: e["type"] for e in pdj["fields"]}   # CLR types (System.Boolean / System.Int32 / ...)
    out = []
    out.append("/* GENERATED by sim/hero/gen_fields.py -- do not edit.")
    out.append(" * Sources: analysis/traces/p0/r2_move.a.hktrace header fields.hero / fields.cstate / fields.playerdata")
    out.append(" *          (docs/trace-format.md #Header), analysis/dumps/GG_Hornet_1/hero.json (field CLR types).")
    out.append(" * X(ctype, cname, \"trace name\", code)   code: 'f' float32, 'i' int32/enum, 'b' bool (i32 on the wire). */")
    out.append("#define HERO_FIELDS(X) \\")
    for e in h["hero"]:
        n, ty = e["name"], e["type"]
        cname = n.replace("<fallTimer>k__BackingField", "fallTimer")
        dtype = hc[n]["type"] if n in hc else None
        if ty == "f32":
            ct, code = "float", "f"
        elif dtype == "System.Boolean":
            ct, code = "uint8_t", "b"
        else:
            ct, code = "int32_t", "i"
        out.append("    X(%s, %s, \"%s\", '%s') \\" % (ct, cname, n, code))
    out[-1] = out[-1].rstrip(" \\")
    out.append("")
    out.append("/* HeroControllerStates public bool fields; bit i of FRAME.cstate = field i")
    out.append(" * cite: analysis/decomp/Assembly-CSharp/HeroControllerStates.cs:7-115 ; docs/trace-format.md #Header */")
    out.append("#define HERO_CSTATE(X) \\")
    for n in h["cstate"]:
        out.append("    X(%s) \\" % n)
    out[-1] = out[-1].rstrip(" \\")
    out.append("")
    out.append("/* PlayerData fields HeroController reads/writes (subset of the 1443 traced; same names) */")
    out.append("#define HERO_PD_FIELDS(X) \\")
    missing = [k for k in PD_KEYS if k not in pd_types]
    if missing:
        raise SystemExit("PD keys not in trace header: %r" % missing)
    for k in PD_KEYS:
        ty = pd_types[k]
        if ty == "f32":
            ct, code = "float", "f"
        elif pd_clr.get(k) == "System.Boolean":
            ct, code = "uint8_t", "b"
        else:
            ct, code = "int32_t", "i"
        out.append("    X(%s, %s, \"%s\", '%s') \\" % (ct, k, k, code))
    out[-1] = out[-1].rstrip(" \\")
    out.append("")
    path = os.path.join(ROOT, "sim", "hero", "hero_fields.h")
    with open(path, "w", newline="\n") as fh:
        fh.write("\n".join(out) + "\n")
    print("wrote", path, len(h["hero"]), "hero fields,", len(h["cstate"]), "cstate bits,", len(PD_KEYS), "pd fields")
    gen_dump_init(h, hero, pdj, pd_clr)


def c_float(v):
    s = "%.9g" % float(v)
    if "." not in s and "e" not in s and "n" not in s:
        s += ".0"
    return s + "f"


# HeroAnimationController fields the sim models, dump name -> hero_anim member (sim/hero/hero.h).
# The auto-properties come out of reflection as their compiler-generated backing fields.
HERO_ANIM_FIELDS = {
    "<controlEnabled>k__BackingField": "controlEnabled",
    "playLanding": "playLanding", "playRunToIdle": "playRunToIdle", "playDashToIdle": "playDashToIdle",
    "playBackDashToIdleEnd": "playBackDashToIdleEnd", "wasAttacking": "wasAttacking",
    "wasFacingRight": "wasFacingRight", "setEntryAnim": "setEntryAnim",
    "changedClipFromLastFrame": "changedClipFromLastFrame", "attackComplete": "attackComplete",
}


# sim/fsm/gen/gen_tables.py's LEGACY_DUMP_SCENES: the 15 already-ported roster arenas stay on their
# original dump source, pinned to the golden fixtures recorded against their current per-scene hero
# overrides; see that constant's comment for the 2026-09-24 measurement.
LEGACY_DUMP_SCENES = {
    "GG_False_Knight", "GG_Ghost_Gorb", "GG_Ghost_Hu", "GG_Ghost_Markoth", "GG_Ghost_Marmu",
    "GG_Ghost_No_Eyes", "GG_Ghost_Xero", "GG_Grimm_Nightmare", "GG_Gruz_Mother", "GG_Gruz_Mother_V",
    "GG_Gruz_Mother_V@T1", "GG_Hornet_1", "GG_Hornet_2", "GG_Mega_Moss_Charger", "GG_Nosk", "GG_Soul_Master",
}


def scene_dump_dirs():
    """Every arena dump the generator knows, as (level key, dump directory).

    analysis/dumps_v2/<scene>__T<bossLevel+1> the 2026-09-24 roster re-dump (one oracle build, one mod
                                commit, every arena/tier); key = scene name at T1, "<scene>@T1"/"@T2"
                                at T2/T3.  Tried FIRST (except for LEGACY_DUMP_SCENES) so the `seen`
                                dedup below prefers it.
    analysis/dumps/<scene>      the dumps the ported scenes' tables are built from (key = scene name)
    analysis/dumps_all/<scene>  every other arena, tier as the statue first-match loads it (key = scene name)
    analysis/dumps_t1|t2/<scene> the same arenas loaded at BossLevel 1 / 2 (meta.json bossLevel; key =
                                "<scene>@T1" / "<scene>@T2", the level string a tier arena is created with)"""
    an = os.path.join(ROOT, "analysis")
    out, seen = [], set()
    v2 = os.path.join(an, "dumps_v2")
    if os.path.isdir(v2):
        import re as _re
        for d in sorted(os.listdir(v2)):
            m = _re.fullmatch(r"(.+)__T(\d)", d)
            if not m or not os.path.exists(os.path.join(v2, d, "hero.json")):
                continue
            scene, bl = m.group(1), int(m.group(2)) - 1
            key = scene if bl == 0 else "%s@T%d" % (scene, bl)
            if key in seen or key in LEGACY_DUMP_SCENES:
                continue
            seen.add(key)
            out.append((key, os.path.join(v2, d), "dumps_v2/%s" % d))
    for sub, suffix in (("dumps", ""), ("dumps_all", ""), ("dumps_t1", "@T1"), ("dumps_t2", "@T2")):
        base = os.path.join(an, sub)
        if not os.path.isdir(base):
            continue
        for d in sorted(os.listdir(base)):
            key = d + suffix
            if key in seen or not os.path.exists(os.path.join(base, d, "hero.json")):
                continue
            seen.add(key)
            out.append((key, os.path.join(base, d), "%s/%s" % (sub, d)))
    return out


def dump_boss_level(ddir):
    """BossSceneController.BossLevel of the dump: meta.json `bossLevel` (oracle SceneDumper).  Absent reads
    as 0: that oracle clamped every load to BossLevel 0 (oracle/HKOracle.cs:147-176)."""
    p = os.path.join(ddir, "meta.json")
    if not os.path.exists(p):
        return 0
    return int(json.load(open(p, encoding="utf-8")).get("bossLevel") or 0)


def knight_anim_fields(ddir):
    """The Knight's HeroAnimationController field dump, by name.  {} when the scene has no hierarchy dump."""
    p = os.path.join(ddir, "hierarchy.json.gz")
    p_plain = os.path.join(ddir, "hierarchy.json")   # dumps_v2 writes this uncompressed
    if os.path.exists(p):
        import gzip
        text = gzip.open(p, "rt", encoding="utf-8").read()
    elif os.path.exists(p_plain):
        text = open(p_plain, encoding="utf-8").read()
    else:
        return {}
    # Decode only the DDOL/Knight object (the whole file is large).  The dumper writes compact JSON with `path`
    # as each object's first key (HierarchyDumper.cs).
    i = text.find('{"path":"DDOL/Knight",')
    if i < 0:
        return {}
    o, _end = json.JSONDecoder(strict=False).raw_decode(text, i)
    for c in o.get("components", []):
        if c.get("type") == "HeroAnimationController":
            return {e["name"]: e for e in (c.get("fields") or [])}
    return {}


def gen_scene_overrides(h, hornet_hc):
    """hero_init_scene(): per-scene overrides of the GG_Hornet_1 base initialiser, for every hero field whose
    dumped value differs from Hornet's (e.g. acceptingInput / controlReqlinquished, held by the opening kneel).

    Also diffs HeroAnimationController (not in hero.json; read from hierarchy.json.gz): controlEnabled is the
    other half of that lock -- `Dream Entry | Control` sends StopAnimationControl before the kneel, and the
    Tk2dWatchAnimationEvents that ends it waits on the cutscene clip, which an enabled HAC would overwrite.
    Both scans are field-by-field diffs, not name lists, so a newly-diverging field is picked up automatically.
    """
    dumps = os.path.join(ROOT, "analysis", "dumps")
    dirs = scene_dump_dirs()
    scenes = [k for k, _d, _c in dirs]
    ddir = {k: d for k, d, _c in dirs}
    cite = {k: c for k, _d, c in dirs}
    names = [e["name"] for e in h["hero"]]
    diff = {}
    for sc in scenes:
        hcs = {e["name"]: e for e in json.load(open(os.path.join(ddir[sc], "hero.json"), encoding="utf-8"))["heroController"]}
        for n in names:
            if n not in hcs:
                continue
            a, b = hornet_hc[n]["value"], hcs[n]["value"]
            if isinstance(a, (dict, list)) or isinstance(b, (dict, list)):
                continue                      # object refs / history, not scalar state
            if a != b:
                diff.setdefault(sc, []).append((n, b, hcs[n]["type"]))
    anim_diff = {}
    base_anim = knight_anim_fields(os.path.join(dumps, "GG_Hornet_1"))
    for sc in scenes:
        for n, e in sorted(knight_anim_fields(ddir[sc]).items()):
            if n not in HERO_ANIM_FIELDS or n not in base_anim:
                continue
            a, b = base_anim[n]["value"], e["value"]
            if isinstance(a, (dict, list)) or isinstance(b, (dict, list)) or a == b:
                continue
            anim_diff.setdefault(sc, []).append((HERO_ANIM_FIELDS[n], b, e["type"]))
    # PlayerData.hazardRespawnLocation is where HC.HazardRespawn puts the knight back after a spike hit.
    # It is per-arena, so it is diffed against Hornet's like the rest.
    hz_base = {e["name"]: e["value"] for e in json.load(open(os.path.join(dumps, "GG_Hornet_1", "playerdata.json"), encoding="utf-8"))["fields"]}["hazardRespawnLocation"]
    hz_diff = {}
    for sc in scenes:
        pdp = os.path.join(ddir[sc], "playerdata.json")
        if not os.path.exists(pdp):
            continue
        pv = {e["name"]: e["value"] for e in json.load(open(pdp, encoding="utf-8"))["fields"]}
        v = pv.get("hazardRespawnLocation")
        if v is not None and (v["x"], v["y"]) != (hz_base["x"], hz_base["y"]):
            hz_diff[sc] = v
    o = ["", "/* Per-scene hero state: the fields whose dumped value differs from GG_Hornet_1's.",
         " * Generated by scanning every arena dump (analysis/dumps_v2 preferred, else dumps, dumps_all,",
         " * dumps_t1, dumps_t2: scene_dump_dirs), so a newly-diverging field appears here automatically",
         " * instead of silently inheriting Hornet's value.",
         " * `scene` is the level key: the scene name, or \"<scene>@T1\" / \"<scene>@T2\" for a tier dump. */",
         "void hero_init_scene(hero *h, const char *scene)", "{", "    (void)h; (void)scene;"]
    lvl = {sc: dump_boss_level(ddir[sc]) for sc in scenes}
    for sc in scenes:
        if not (diff.get(sc) or anim_diff.get(sc) or hz_diff.get(sc) or lvl[sc]):
            continue
        o.append("    if (!strcmp(scene, \"%s\")) {" % sc)
        if lvl[sc]:
            o.append("        h->bsc_bossLevel = %d; /* cite: %s/meta.json#bossLevel; read by HC:1835 */" % (lvl[sc], cite[sc]))
        if sc in hz_diff:
            o.append("        h->hazardRespawnLocation.x = %s; h->hazardRespawnLocation.y = %s;"
                     " /* cite: %s/playerdata.json#hazardRespawnLocation */"
                     % (c_float(hz_diff[sc]["x"]), c_float(hz_diff[sc]["y"]), cite[sc]))
        hier_name = "hierarchy.json" if os.path.exists(os.path.join(ddir[sc], "hierarchy.json")) else "hierarchy.json.gz"
        for n, v, ty in anim_diff.get(sc, []):
            o.append("        h->anim.%s = %s; /* cite: %s/%s#DDOL/Knight HeroAnimationController */"
                     % (n, "1" if v else "0", cite[sc], hier_name))
        for n, v, ty in diff.get(sc, []):
            cname = n.replace("<fallTimer>k__BackingField", "fallTimer")
            if isinstance(v, dict) and "__enum" in v:
                lit = str(int(v["value"]))
            elif ty == "System.Boolean":
                lit = "1" if v else "0"
            elif ty == "System.Single":
                lit = c_float(v)
            else:
                lit = str(int(v))
            o.append("        h->f.%s = %s; /* cite: %s/hero.json#%s */" % (cname, lit, cite[sc], n))
        o.append("    }")
    o.append("}")
    print("  per-scene hero overrides: %s" % {k: [n for n, _v, _t in v] for k, v in diff.items()})
    print("  per-scene HAC overrides:   %s" % {k: [n for n, _v, _t in v] for k, v in anim_diff.items()})
    return o


def gen_dump_init(h, hero, pdj, pd_clr):
    """hero_dump_init.c: hero_init_from_dump() -- every value cites the dump key it came from."""
    hc = {e["name"]: e for e in hero["heroController"]}
    cst = {e["name"]: e["value"] for e in hero["cState"]}
    pdv = {e["name"]: e["value"] for e in pdj["fields"]}
    phys = json.load(open(os.path.join(ROOT, "analysis", "dumps", "GG_Hornet_1", "physics.json")))
    col = phys["heroColliders"][0]
    o = []
    o.append("/* GENERATED by sim/hero/gen_fields.py -- do not edit.  Initial hero state = the SceneReady reflection dump")
    o.append(" * (analysis/dumps/GG_Hornet_1/{hero,playerdata,physics}.json; meta.json timestampUtc 2026-08-31T02:49:29Z). */")
    o.append("#include <string.h>")
    o.append("#include \"hero/hero.h\"")
    o.append("")
    o.append("void hero_init_from_dump(hero *h)")
    o.append("{")
    o.append("    memset(h, 0, sizeof *h);")
    o.append("    hero_input_init(&h->in);")
    for e in h["hero"]:
        n = e["name"]
        cname = n.replace("<fallTimer>k__BackingField", "fallTimer")
        d = hc[n]
        v, ty = d["value"], d["type"]
        if isinstance(v, dict) and "__enum" in v:
            lit = str(int(v["value"]))
        elif ty == "System.Boolean":
            lit = "1" if v else "0"
        elif ty == "System.Single":
            lit = c_float(v)
        else:
            lit = str(int(v))
        o.append("    h->f.%s = %s; /* cite: dumps/GG_Hornet_1/hero.json#%s */" % (cname, lit, n))
    for n in ("slashOffset", "upSlashOffset", "downwardSlashOffset", "spell1Offset", "current_velocity",
              "transition_vel", "recoilVector", "lastInputState", "oldPos"):
        v = hc[n]["value"]
        o.append("    h->f.%s.x = %s; h->f.%s.y = %s; /* cite: dumps/GG_Hornet_1/hero.json#%s */"
                 % (n, c_float(v["x"]), n, c_float(v["y"]), n))
    ph = hc["positionHistory"]["value"]
    for i in range(2):
        o.append("    h->f.positionHistory[%d].x = %s; h->f.positionHistory[%d].y = %s; /* cite: dumps/GG_Hornet_1/hero.json#positionHistory */"
                 % (i, c_float(ph[i]["x"]), i, c_float(ph[i]["y"])))
    for n in h["cstate"]:
        o.append("    h->cs.%s = %d; /* cite: dumps/GG_Hornet_1/hero.json#cState.%s */" % (n, 1 if cst[n] else 0, n))
    for k in PD_KEYS:
        v = pdv[k]
        if pd_clr[k] == "System.Boolean":
            lit = "1" if v else "0"
        elif pd_clr[k] == "System.Single":
            lit = c_float(v)
        else:
            lit = str(int(v))
        o.append("    h->pd.%s = %s; /* cite: dumps/GG_Hornet_1/playerdata.json#%s */" % (k, lit, k))
    hz = pdv["hazardRespawnLocation"]
    o.append("    h->hazardRespawnLocation.x = %s; h->hazardRespawnLocation.y = %s;"
             " /* cite: dumps/GG_Hornet_1/playerdata.json#hazardRespawnLocation */"
             % (c_float(hz["x"]), c_float(hz["y"])))
    o.append("    h->col_offset.x = %s; h->col_offset.y = %s; /* cite: dumps/GG_Hornet_1/physics.json#heroColliders[0].offset */"
             % (c_float(col["offset"]["x"]), c_float(col["offset"]["y"])))
    o.append("    h->col_size.x = %s; h->col_size.y = %s; /* cite: dumps/GG_Hornet_1/physics.json#heroColliders[0].size */"
             % (c_float(col["size"]["x"]), c_float(col["size"]["y"])))
    o.append("    h->col_edgeRadius = %s; /* cite: dumps/GG_Hornet_1/physics.json#heroColliders[0].edgeRadius */"
             % c_float(col["edgeRadius"]))
    o.append("    h->gameObject_layer = %d; /* cite: dumps/GG_Hornet_1/hero.json#gameObject.layer */" % hero["gameObject"]["layer"])
    o.append("    h->slashComponent = SLASH_NONE; /* cite: dumps/GG_Hornet_1/hero.json#slashComponent (null) */")
    o.append("    h->heroBox_inactive = 0; /* HeroBox.inactive = false: HC:881 (SceneInit, gameplay scene) */")
    o.append("    h->gm_isPaused = 0; h->gm_isGameplayScene = 1; /* hero.json#isGameplayScene = true; the env never pauses */")
    o.append("    h->gm_mapZoneIsDreamOrGG = 1; /* GG_* scenes are map zone GODS_GLORY: damage-path.md 1.6 */")
    o.append("    h->bsc_isBossScene = 1; h->bsc_isTransitioning = 0; h->bsc_bossLevel = 0; /* damage-path.md 1.2 item 3; a tier dump's meta.json bossLevel overrides it in hero_init_scene */")
    o.append("    for (int i = 0; i < SLASH_N; i++) h->slash[i].longnail = h->slash[i].mantis = 0; /* charms 13/18: Slash Size Modifiers FSM (worker F) */")
    o.append("    hero_anim_init(h); /* HeroAnimationController state (HAC:42-53); the animator is already on Idle: physics.json#heroAnimator */")
    o.append("}")
    o.extend(gen_scene_overrides(h, hc))
    path = os.path.join(ROOT, "sim", "hero", "hero_dump_init.c")
    with open(path, "w", newline="\n") as fh:
        fh.write("\n".join(o) + "\n")
    print("wrote", path)


if __name__ == "__main__":
    # Provenance sidecar for gate/inputs_fresh.py (see sim/fsm/gen/input_stamp.py).
    sys.path.insert(0, os.path.join(ROOT, "sim", "fsm", "gen"))
    from input_stamp import InputStamp
    with InputStamp(os.path.join(ROOT, "sim", "hero", "hero_dump_init.inputs.json"),
                    scene="*", generator="sim/hero/gen_fields.py"):
        main()
