/* GENERATED by sim/hero/gen_fields.py -- do not edit.
 * Sources: analysis/traces/p0/r2_move.a.hktrace header fields.hero / fields.cstate / fields.playerdata
 *          (docs/trace-format.md #Header), analysis/dumps/GG_Hornet_1/hero.json (field CLR types).
 * X(ctype, cname, "trace name", code)   code: 'f' float32, 'i' int32/enum, 'b' bool (i32 on the wire). */
#define HERO_FIELDS(X) \
    X(uint8_t, verboseMode, "verboseMode", 'b') \
    X(int32_t, heroType, "heroType", 'i') \
    X(float, RUN_SPEED, "RUN_SPEED", 'f') \
    X(float, RUN_SPEED_CH, "RUN_SPEED_CH", 'f') \
    X(float, RUN_SPEED_CH_COMBO, "RUN_SPEED_CH_COMBO", 'f') \
    X(float, WALK_SPEED, "WALK_SPEED", 'f') \
    X(float, UNDERWATER_SPEED, "UNDERWATER_SPEED", 'f') \
    X(float, JUMP_SPEED, "JUMP_SPEED", 'f') \
    X(float, JUMP_SPEED_UNDERWATER, "JUMP_SPEED_UNDERWATER", 'f') \
    X(float, MIN_JUMP_SPEED, "MIN_JUMP_SPEED", 'f') \
    X(int32_t, JUMP_STEPS, "JUMP_STEPS", 'i') \
    X(int32_t, JUMP_STEPS_MIN, "JUMP_STEPS_MIN", 'i') \
    X(int32_t, JUMP_TIME, "JUMP_TIME", 'i') \
    X(int32_t, DOUBLE_JUMP_STEPS, "DOUBLE_JUMP_STEPS", 'i') \
    X(int32_t, WJLOCK_STEPS_SHORT, "WJLOCK_STEPS_SHORT", 'i') \
    X(int32_t, WJLOCK_STEPS_LONG, "WJLOCK_STEPS_LONG", 'i') \
    X(float, WJ_KICKOFF_SPEED, "WJ_KICKOFF_SPEED", 'f') \
    X(int32_t, WALL_STICKY_STEPS, "WALL_STICKY_STEPS", 'i') \
    X(float, DASH_SPEED, "DASH_SPEED", 'f') \
    X(float, DASH_SPEED_SHARP, "DASH_SPEED_SHARP", 'f') \
    X(float, DASH_TIME, "DASH_TIME", 'f') \
    X(int32_t, DASH_QUEUE_STEPS, "DASH_QUEUE_STEPS", 'i') \
    X(float, BACK_DASH_SPEED, "BACK_DASH_SPEED", 'f') \
    X(float, BACK_DASH_TIME, "BACK_DASH_TIME", 'f') \
    X(float, SHADOW_DASH_SPEED, "SHADOW_DASH_SPEED", 'f') \
    X(float, SHADOW_DASH_TIME, "SHADOW_DASH_TIME", 'f') \
    X(float, SHADOW_DASH_COOLDOWN, "SHADOW_DASH_COOLDOWN", 'f') \
    X(float, SUPER_DASH_SPEED, "SUPER_DASH_SPEED", 'f') \
    X(float, DASH_COOLDOWN, "DASH_COOLDOWN", 'f') \
    X(float, DASH_COOLDOWN_CH, "DASH_COOLDOWN_CH", 'f') \
    X(float, BACKDASH_COOLDOWN, "BACKDASH_COOLDOWN", 'f') \
    X(float, WALLSLIDE_SPEED, "WALLSLIDE_SPEED", 'f') \
    X(float, WALLSLIDE_DECEL, "WALLSLIDE_DECEL", 'f') \
    X(float, NAIL_CHARGE_TIME_DEFAULT, "NAIL_CHARGE_TIME_DEFAULT", 'f') \
    X(float, NAIL_CHARGE_TIME_CHARM, "NAIL_CHARGE_TIME_CHARM", 'f') \
    X(float, CYCLONE_HORIZONTAL_SPEED, "CYCLONE_HORIZONTAL_SPEED", 'f') \
    X(float, SWIM_ACCEL, "SWIM_ACCEL", 'f') \
    X(float, SWIM_MAX_SPEED, "SWIM_MAX_SPEED", 'f') \
    X(float, TIME_TO_ENTER_SCENE_BOT, "TIME_TO_ENTER_SCENE_BOT", 'f') \
    X(float, TIME_TO_ENTER_SCENE_HOR, "TIME_TO_ENTER_SCENE_HOR", 'f') \
    X(float, SPEED_TO_ENTER_SCENE_HOR, "SPEED_TO_ENTER_SCENE_HOR", 'f') \
    X(float, SPEED_TO_ENTER_SCENE_UP, "SPEED_TO_ENTER_SCENE_UP", 'f') \
    X(float, SPEED_TO_ENTER_SCENE_DOWN, "SPEED_TO_ENTER_SCENE_DOWN", 'f') \
    X(float, DEFAULT_GRAVITY, "DEFAULT_GRAVITY", 'f') \
    X(float, UNDERWATER_GRAVITY, "UNDERWATER_GRAVITY", 'f') \
    X(float, ATTACK_DURATION, "ATTACK_DURATION", 'f') \
    X(float, ATTACK_DURATION_CH, "ATTACK_DURATION_CH", 'f') \
    X(float, ALT_ATTACK_RESET, "ALT_ATTACK_RESET", 'f') \
    X(float, ATTACK_RECOVERY_TIME, "ATTACK_RECOVERY_TIME", 'f') \
    X(float, ATTACK_COOLDOWN_TIME, "ATTACK_COOLDOWN_TIME", 'f') \
    X(float, ATTACK_COOLDOWN_TIME_CH, "ATTACK_COOLDOWN_TIME_CH", 'f') \
    X(float, BOUNCE_TIME, "BOUNCE_TIME", 'f') \
    X(float, BOUNCE_SHROOM_TIME, "BOUNCE_SHROOM_TIME", 'f') \
    X(float, BOUNCE_VELOCITY, "BOUNCE_VELOCITY", 'f') \
    X(float, SHROOM_BOUNCE_VELOCITY, "SHROOM_BOUNCE_VELOCITY", 'f') \
    X(float, RECOIL_HOR_TIME, "RECOIL_HOR_TIME", 'f') \
    X(float, RECOIL_HOR_VELOCITY, "RECOIL_HOR_VELOCITY", 'f') \
    X(float, RECOIL_HOR_VELOCITY_LONG, "RECOIL_HOR_VELOCITY_LONG", 'f') \
    X(float, RECOIL_HOR_STEPS, "RECOIL_HOR_STEPS", 'f') \
    X(float, RECOIL_DOWN_VELOCITY, "RECOIL_DOWN_VELOCITY", 'f') \
    X(float, RUN_PUFF_TIME, "RUN_PUFF_TIME", 'f') \
    X(float, BIG_FALL_TIME, "BIG_FALL_TIME", 'f') \
    X(float, HARD_LANDING_TIME, "HARD_LANDING_TIME", 'f') \
    X(float, DOWN_DASH_TIME, "DOWN_DASH_TIME", 'f') \
    X(float, MAX_FALL_VELOCITY, "MAX_FALL_VELOCITY", 'f') \
    X(float, MAX_FALL_VELOCITY_UNDERWATER, "MAX_FALL_VELOCITY_UNDERWATER", 'f') \
    X(float, RECOIL_DURATION, "RECOIL_DURATION", 'f') \
    X(float, RECOIL_DURATION_STAL, "RECOIL_DURATION_STAL", 'f') \
    X(float, RECOIL_VELOCITY, "RECOIL_VELOCITY", 'f') \
    X(float, DAMAGE_FREEZE_DOWN, "DAMAGE_FREEZE_DOWN", 'f') \
    X(float, DAMAGE_FREEZE_WAIT, "DAMAGE_FREEZE_WAIT", 'f') \
    X(float, DAMAGE_FREEZE_UP, "DAMAGE_FREEZE_UP", 'f') \
    X(float, INVUL_TIME, "INVUL_TIME", 'f') \
    X(float, INVUL_TIME_STAL, "INVUL_TIME_STAL", 'f') \
    X(float, INVUL_TIME_PARRY, "INVUL_TIME_PARRY", 'f') \
    X(float, INVUL_TIME_QUAKE, "INVUL_TIME_QUAKE", 'f') \
    X(float, INVUL_TIME_CYCLONE, "INVUL_TIME_CYCLONE", 'f') \
    X(float, CAST_TIME, "CAST_TIME", 'f') \
    X(float, CAST_RECOIL_TIME, "CAST_RECOIL_TIME", 'f') \
    X(float, CAST_RECOIL_VELOCITY, "CAST_RECOIL_VELOCITY", 'f') \
    X(float, WALLSLIDE_CLIP_DELAY, "WALLSLIDE_CLIP_DELAY", 'f') \
    X(int32_t, GRUB_SOUL_MP, "GRUB_SOUL_MP", 'i') \
    X(int32_t, GRUB_SOUL_MP_COMBO, "GRUB_SOUL_MP_COMBO", 'i') \
    X(int32_t, JUMP_QUEUE_STEPS, "JUMP_QUEUE_STEPS", 'i') \
    X(int32_t, JUMP_RELEASE_QUEUE_STEPS, "JUMP_RELEASE_QUEUE_STEPS", 'i') \
    X(int32_t, DOUBLE_JUMP_QUEUE_STEPS, "DOUBLE_JUMP_QUEUE_STEPS", 'i') \
    X(int32_t, ATTACK_QUEUE_STEPS, "ATTACK_QUEUE_STEPS", 'i') \
    X(float, DELAY_BEFORE_ENTER, "DELAY_BEFORE_ENTER", 'f') \
    X(float, LOOK_DELAY, "LOOK_DELAY", 'f') \
    X(float, LOOK_ANIM_DELAY, "LOOK_ANIM_DELAY", 'f') \
    X(float, DEATH_WAIT, "DEATH_WAIT", 'f') \
    X(float, HAZARD_DEATH_CHECK_TIME, "HAZARD_DEATH_CHECK_TIME", 'f') \
    X(float, FLOATING_CHECK_TIME, "FLOATING_CHECK_TIME", 'f') \
    X(float, NAIL_TERRAIN_CHECK_TIME, "NAIL_TERRAIN_CHECK_TIME", 'f') \
    X(float, BUMP_VELOCITY, "BUMP_VELOCITY", 'f') \
    X(float, BUMP_VELOCITY_DASH, "BUMP_VELOCITY_DASH", 'f') \
    X(int32_t, LANDING_BUFFER_STEPS, "LANDING_BUFFER_STEPS", 'i') \
    X(int32_t, LEDGE_BUFFER_STEPS, "LEDGE_BUFFER_STEPS", 'i') \
    X(int32_t, HEAD_BUMP_STEPS, "HEAD_BUMP_STEPS", 'i') \
    X(float, MANTIS_CHARM_SCALE, "MANTIS_CHARM_SCALE", 'f') \
    X(float, FIND_GROUND_POINT_DISTANCE, "FIND_GROUND_POINT_DISTANCE", 'f') \
    X(float, FIND_GROUND_POINT_DISTANCE_EXT, "FIND_GROUND_POINT_DISTANCE_EXT", 'f') \
    X(int32_t, hero_state, "hero_state", 'i') \
    X(int32_t, prev_hero_state, "prev_hero_state", 'i') \
    X(int32_t, transitionState, "transitionState", 'i') \
    X(int32_t, damageMode, "damageMode", 'i') \
    X(float, move_input, "move_input", 'f') \
    X(float, vertical_input, "vertical_input", 'f') \
    X(float, controller_deadzone, "controller_deadzone", 'f') \
    X(uint8_t, isGameplayScene, "isGameplayScene", 'b') \
    X(uint8_t, isEnteringFirstLevel, "isEnteringFirstLevel", 'b') \
    X(int32_t, jump_steps, "jump_steps", 'i') \
    X(int32_t, jumped_steps, "jumped_steps", 'i') \
    X(int32_t, doubleJump_steps, "doubleJump_steps", 'i') \
    X(float, dash_timer, "dash_timer", 'f') \
    X(float, back_dash_timer, "back_dash_timer", 'f') \
    X(float, shadow_dash_timer, "shadow_dash_timer", 'f') \
    X(float, attack_time, "attack_time", 'f') \
    X(float, attack_cooldown, "attack_cooldown", 'f') \
    X(float, altAttackTime, "altAttackTime", 'f') \
    X(float, lookDelayTimer, "lookDelayTimer", 'f') \
    X(float, bounceTimer, "bounceTimer", 'f') \
    X(float, recoilHorizontalTimer, "recoilHorizontalTimer", 'f') \
    X(float, runPuffTimer, "runPuffTimer", 'f') \
    X(float, fallTimer, "<fallTimer>k__BackingField", 'f') \
    X(float, hardLandingTimer, "hardLandingTimer", 'f') \
    X(float, dashLandingTimer, "dashLandingTimer", 'f') \
    X(float, recoilTimer, "recoilTimer", 'f') \
    X(int32_t, recoilSteps, "recoilSteps", 'i') \
    X(int32_t, landingBufferSteps, "landingBufferSteps", 'i') \
    X(int32_t, dashQueueSteps, "dashQueueSteps", 'i') \
    X(uint8_t, dashQueuing, "dashQueuing", 'b') \
    X(float, shadowDashTimer, "shadowDashTimer", 'f') \
    X(float, dashCooldownTimer, "dashCooldownTimer", 'f') \
    X(float, nailChargeTimer, "nailChargeTimer", 'f') \
    X(int32_t, wallLockSteps, "wallLockSteps", 'i') \
    X(float, wallslideClipTimer, "wallslideClipTimer", 'f') \
    X(float, hardLandFailSafeTimer, "hardLandFailSafeTimer", 'f') \
    X(float, hazardDeathTimer, "hazardDeathTimer", 'f') \
    X(float, floatingBufferTimer, "floatingBufferTimer", 'f') \
    X(float, attackDuration, "attackDuration", 'f') \
    X(float, parryInvulnTimer, "parryInvulnTimer", 'f') \
    X(float, prevGravityScale, "prevGravityScale", 'f') \
    X(int32_t, gatePosition, "gatePosition", 'i') \
    X(uint8_t, runMsgSent, "runMsgSent", 'b') \
    X(uint8_t, hardLanded, "hardLanded", 'b') \
    X(uint8_t, fallRumble, "fallRumble", 'b') \
    X(uint8_t, acceptingInput, "acceptingInput", 'b') \
    X(uint8_t, fallTrailGenerated, "fallTrailGenerated", 'b') \
    X(uint8_t, drainMP, "drainMP", 'b') \
    X(float, drainMP_timer, "drainMP_timer", 'f') \
    X(float, drainMP_time, "drainMP_time", 'f') \
    X(float, MP_drained, "MP_drained", 'f') \
    X(float, drainMP_seconds, "drainMP_seconds", 'f') \
    X(float, focusMP_amount, "focusMP_amount", 'f') \
    X(float, dashBumpCorrection, "dashBumpCorrection", 'f') \
    X(uint8_t, controlReqlinquished, "controlReqlinquished", 'b') \
    X(uint8_t, enterWithoutInput, "enterWithoutInput", 'b') \
    X(uint8_t, lookingUpAnim, "lookingUpAnim", 'b') \
    X(uint8_t, lookingDownAnim, "lookingDownAnim", 'b') \
    X(uint8_t, carefreeShieldEquipped, "carefreeShieldEquipped", 'b') \
    X(int32_t, hitsSinceShielded, "hitsSinceShielded", 'i') \
    X(int32_t, jumpQueueSteps, "jumpQueueSteps", 'i') \
    X(uint8_t, jumpQueuing, "jumpQueuing", 'b') \
    X(int32_t, doubleJumpQueueSteps, "doubleJumpQueueSteps", 'i') \
    X(uint8_t, doubleJumpQueuing, "doubleJumpQueuing", 'b') \
    X(int32_t, jumpReleaseQueueSteps, "jumpReleaseQueueSteps", 'i') \
    X(uint8_t, jumpReleaseQueuing, "jumpReleaseQueuing", 'b') \
    X(int32_t, attackQueueSteps, "attackQueueSteps", 'i') \
    X(uint8_t, attackQueuing, "attackQueuing", 'b') \
    X(uint8_t, touchingWallL, "touchingWallL", 'b') \
    X(uint8_t, touchingWallR, "touchingWallR", 'b') \
    X(uint8_t, wallSlidingL, "wallSlidingL", 'b') \
    X(uint8_t, wallSlidingR, "wallSlidingR", 'b') \
    X(uint8_t, airDashed, "airDashed", 'b') \
    X(uint8_t, dashingDown, "dashingDown", 'b') \
    X(uint8_t, wieldingLantern, "wieldingLantern", 'b') \
    X(uint8_t, startWithWallslide, "startWithWallslide", 'b') \
    X(uint8_t, startWithJump, "startWithJump", 'b') \
    X(uint8_t, startWithFullJump, "startWithFullJump", 'b') \
    X(uint8_t, startWithDash, "startWithDash", 'b') \
    X(uint8_t, startWithAttack, "startWithAttack", 'b') \
    X(uint8_t, nailArt_cyclone, "nailArt_cyclone", 'b') \
    X(uint8_t, wallSlashing, "wallSlashing", 'b') \
    X(uint8_t, doubleJumped, "doubleJumped", 'b') \
    X(uint8_t, inAcid, "inAcid", 'b') \
    X(uint8_t, wallJumpedR, "wallJumpedR", 'b') \
    X(uint8_t, wallJumpedL, "wallJumpedL", 'b') \
    X(uint8_t, wallLocked, "wallLocked", 'b') \
    X(float, currentWalljumpSpeed, "currentWalljumpSpeed", 'f') \
    X(float, walljumpSpeedDecel, "walljumpSpeedDecel", 'f') \
    X(int32_t, wallUnstickSteps, "wallUnstickSteps", 'i') \
    X(uint8_t, recoilLarge, "recoilLarge", 'b') \
    X(float, conveyorSpeed, "conveyorSpeed", 'f') \
    X(float, conveyorSpeedV, "conveyorSpeedV", 'f') \
    X(uint8_t, enteringVertically, "enteringVertically", 'b') \
    X(uint8_t, playingWallslideClip, "playingWallslideClip", 'b') \
    X(uint8_t, playedMantisClawClip, "playedMantisClawClip", 'b') \
    X(uint8_t, exitedSuperDashing, "exitedSuperDashing", 'b') \
    X(uint8_t, exitedQuake, "exitedQuake", 'b') \
    X(uint8_t, fallCheckFlagged, "fallCheckFlagged", 'b') \
    X(int32_t, ledgeBufferSteps, "ledgeBufferSteps", 'i') \
    X(int32_t, headBumpSteps, "headBumpSteps", 'i') \
    X(float, nailChargeTime, "nailChargeTime", 'f') \
    X(uint8_t, takeNoDamage, "takeNoDamage", 'b') \
    X(uint8_t, joniBeam, "joniBeam", 'b') \
    X(uint8_t, fadedSceneIn, "fadedSceneIn", 'b') \
    X(uint8_t, stopWalkingOut, "stopWalkingOut", 'b') \
    X(uint8_t, boundsChecking, "boundsChecking", 'b') \
    X(uint8_t, blockerFix, "blockerFix", 'b') \
    X(uint8_t, tilemapTestActive, "tilemapTestActive", 'b') \
    X(uint8_t, isHeroInPosition, "isHeroInPosition", 'b') \
    X(uint8_t, jumpReleaseQueueingEnabled, "jumpReleaseQueueingEnabled", 'b') \
    X(float, preventCastByDialogueEndTimer, "preventCastByDialogueEndTimer", 'f')

/* HeroControllerStates public bool fields; bit i of FRAME.cstate = field i
 * cite: analysis/decomp/Assembly-CSharp/HeroControllerStates.cs:7-115 ; docs/trace-format.md #Header */
#define HERO_CSTATE(X) \
    X(facingRight) \
    X(onGround) \
    X(jumping) \
    X(wallJumping) \
    X(doubleJumping) \
    X(nailCharging) \
    X(shadowDashing) \
    X(swimming) \
    X(falling) \
    X(dashing) \
    X(superDashing) \
    X(superDashOnWall) \
    X(backDashing) \
    X(touchingWall) \
    X(wallSliding) \
    X(transitioning) \
    X(attacking) \
    X(lookingUp) \
    X(lookingDown) \
    X(lookingUpAnim) \
    X(lookingDownAnim) \
    X(altAttack) \
    X(upAttacking) \
    X(downAttacking) \
    X(bouncing) \
    X(shroomBouncing) \
    X(recoilingRight) \
    X(recoilingLeft) \
    X(dead) \
    X(hazardDeath) \
    X(hazardRespawning) \
    X(willHardLand) \
    X(recoilFrozen) \
    X(recoiling) \
    X(invulnerable) \
    X(casting) \
    X(castRecoiling) \
    X(preventDash) \
    X(preventBackDash) \
    X(dashCooldown) \
    X(backDashCooldown) \
    X(nearBench) \
    X(inWalkZone) \
    X(isPaused) \
    X(onConveyor) \
    X(onConveyorV) \
    X(inConveyorZone) \
    X(spellQuake) \
    X(freezeCharge) \
    X(focusing) \
    X(inAcid) \
    X(slidingLeft) \
    X(slidingRight) \
    X(touchingNonSlider) \
    X(wasOnGround)

/* PlayerData fields HeroController reads/writes (subset of the 1443 traced; same names) */
#define HERO_PD_FIELDS(X) \
    X(int32_t, health, "health", 'i') \
    X(int32_t, maxHealth, "maxHealth", 'i') \
    X(int32_t, maxHealthBase, "maxHealthBase", 'i') \
    X(int32_t, healthBlue, "healthBlue", 'i') \
    X(int32_t, joniHealthBlue, "joniHealthBlue", 'i') \
    X(uint8_t, damagedBlue, "damagedBlue", 'b') \
    X(int32_t, prevHealth, "prevHealth", 'i') \
    X(int32_t, blockerHits, "blockerHits", 'i') \
    X(int32_t, MPCharge, "MPCharge", 'i') \
    X(int32_t, maxMP, "maxMP", 'i') \
    X(int32_t, MPReserve, "MPReserve", 'i') \
    X(int32_t, MPReserveMax, "MPReserveMax", 'i') \
    X(uint8_t, soulLimited, "soulLimited", 'b') \
    X(int32_t, focusMP_amount, "focusMP_amount", 'i') \
    X(uint8_t, disablePause, "disablePause", 'b') \
    X(uint8_t, isInvincible, "isInvincible", 'b') \
    X(uint8_t, invinciTest, "invinciTest", 'b') \
    X(uint8_t, infiniteAirJump, "infiniteAirJump", 'b') \
    X(uint8_t, overcharmed, "overcharmed", 'b') \
    X(uint8_t, betaEnd, "betaEnd", 'b') \
    X(int32_t, permadeathMode, "permadeathMode", 'i') \
    X(uint8_t, hasDash, "hasDash", 'b') \
    X(uint8_t, canDash, "canDash", 'b') \
    X(uint8_t, hasWalljump, "hasWalljump", 'b') \
    X(uint8_t, canWallJump, "canWallJump", 'b') \
    X(uint8_t, hasDoubleJump, "hasDoubleJump", 'b') \
    X(uint8_t, hasSuperDash, "hasSuperDash", 'b') \
    X(uint8_t, hasShadowDash, "hasShadowDash", 'b') \
    X(uint8_t, hasDreamNail, "hasDreamNail", 'b') \
    X(uint8_t, hasNailArt, "hasNailArt", 'b') \
    X(uint8_t, hasAcidArmour, "hasAcidArmour", 'b') \
    X(uint8_t, hasLantern, "hasLantern", 'b') \
    X(uint8_t, canBackDash, "canBackDash", 'b') \
    X(uint8_t, hasDreamGate, "hasDreamGate", 'b') \
    X(uint8_t, atBench, "atBench", 'b') \
    X(int32_t, respawnType, "respawnType", 'i') \
    X(int32_t, environmentType, "environmentType", 'i') \
    X(int32_t, grimmChildLevel, "grimmChildLevel", 'i') \
    X(uint8_t, hazardRespawnFacingRight, "hazardRespawnFacingRight", 'b') \
    X(uint8_t, brokenCharm_23, "brokenCharm_23", 'b') \
    X(uint8_t, killedBlocker, "killedBlocker", 'b') \
    X(int32_t, killsBlocker, "killsBlocker", 'i') \
    X(uint8_t, equippedCharm_1, "equippedCharm_1", 'b') \
    X(uint8_t, equippedCharm_2, "equippedCharm_2", 'b') \
    X(uint8_t, equippedCharm_3, "equippedCharm_3", 'b') \
    X(uint8_t, equippedCharm_4, "equippedCharm_4", 'b') \
    X(uint8_t, equippedCharm_5, "equippedCharm_5", 'b') \
    X(uint8_t, equippedCharm_6, "equippedCharm_6", 'b') \
    X(uint8_t, equippedCharm_7, "equippedCharm_7", 'b') \
    X(uint8_t, equippedCharm_8, "equippedCharm_8", 'b') \
    X(uint8_t, equippedCharm_9, "equippedCharm_9", 'b') \
    X(uint8_t, equippedCharm_10, "equippedCharm_10", 'b') \
    X(uint8_t, equippedCharm_11, "equippedCharm_11", 'b') \
    X(uint8_t, equippedCharm_12, "equippedCharm_12", 'b') \
    X(uint8_t, equippedCharm_13, "equippedCharm_13", 'b') \
    X(uint8_t, equippedCharm_14, "equippedCharm_14", 'b') \
    X(uint8_t, equippedCharm_15, "equippedCharm_15", 'b') \
    X(uint8_t, equippedCharm_16, "equippedCharm_16", 'b') \
    X(uint8_t, equippedCharm_17, "equippedCharm_17", 'b') \
    X(uint8_t, equippedCharm_18, "equippedCharm_18", 'b') \
    X(uint8_t, equippedCharm_19, "equippedCharm_19", 'b') \
    X(uint8_t, equippedCharm_20, "equippedCharm_20", 'b') \
    X(uint8_t, equippedCharm_21, "equippedCharm_21", 'b') \
    X(uint8_t, equippedCharm_22, "equippedCharm_22", 'b') \
    X(uint8_t, equippedCharm_23, "equippedCharm_23", 'b') \
    X(uint8_t, equippedCharm_24, "equippedCharm_24", 'b') \
    X(uint8_t, equippedCharm_25, "equippedCharm_25", 'b') \
    X(uint8_t, equippedCharm_26, "equippedCharm_26", 'b') \
    X(uint8_t, equippedCharm_27, "equippedCharm_27", 'b') \
    X(uint8_t, equippedCharm_28, "equippedCharm_28", 'b') \
    X(uint8_t, equippedCharm_29, "equippedCharm_29", 'b') \
    X(uint8_t, equippedCharm_30, "equippedCharm_30", 'b') \
    X(uint8_t, equippedCharm_31, "equippedCharm_31", 'b') \
    X(uint8_t, equippedCharm_32, "equippedCharm_32", 'b') \
    X(uint8_t, equippedCharm_33, "equippedCharm_33", 'b') \
    X(uint8_t, equippedCharm_34, "equippedCharm_34", 'b') \
    X(uint8_t, equippedCharm_35, "equippedCharm_35", 'b') \
    X(uint8_t, equippedCharm_36, "equippedCharm_36", 'b') \
    X(uint8_t, equippedCharm_37, "equippedCharm_37", 'b') \
    X(uint8_t, equippedCharm_38, "equippedCharm_38", 'b') \
    X(uint8_t, equippedCharm_39, "equippedCharm_39", 'b') \
    X(uint8_t, equippedCharm_40, "equippedCharm_40", 'b')

