"""Generate the three registry .inc files from what is actually on disk.

CMake globs every .c in a module dir; the registries are globbed the same way, so adding a scene or
an action file never edits a shared list.
  sim/generated/<NAME>/scene.c   defines  const hk_scene_def *hk_scene_<NAME>(void);
  sim/generated/<NAME>/tables.c  defines  const hkfsm_scene_def hkfsm_scene_<NAME>;
  sim/fsm/**/*.c                 defines  act_registry_<NAME>[] and act_registry_<NAME>_n (unique NAME)

Outputs are gitignored and rewritten only when the content changes, so an unchanged registry forces
no rebuild.
"""
import os, re, sys

SIM = os.path.dirname(os.path.abspath(__file__))
BANNER = "/* GENERATED by sim/gen_registries.py from the files on disk - do not edit, do not commit. */\n"


def write_if_changed(path, text):
    old = None
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8", newline="") as f:
            old = f.read()
    if old == text:
        return False
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(text)
    return True


def generated(fname):
    """Scene names that have sim/generated/<name>/<fname>."""
    root = os.path.join(SIM, "generated")
    return [d for d in sorted(os.listdir(root)) if os.path.isfile(os.path.join(root, d, fname))]


def gen_core_scenes():
    """sim/core/scene_registry.inc -- the hk_scene_def lookup table.

    hk_scene_<NAME>() is a call, not a constant, so the table holds function pointers and the
    caller invokes them; that keeps the whole thing statically initialised.
    """
    ns = generated("scene.c")
    L = [BANNER, '#include "core/scene.h"\n\n']
    for n in ns:
        L.append("HKSIM_API const hk_scene_def *hk_scene_" + n + "(void);\n")
    L.append("\ntypedef const hk_scene_def *(*hk_scene_fn)(void);\n")
    L.append("static const hk_scene_fn HK_REGISTRY_SCENES[] = {\n")
    for n in ns:
        L.append("    hk_scene_" + n + ",\n")
    L.append("};\n")
    return "".join(L), ns


def gen_fsm_scenes():
    """sim/fsm/fsm_scene_registry.inc -- the hkfsm_scene_def lookup table."""
    ns = generated("tables.c")
    L = [BANNER, '#include "fsm/fsm_tables.h"\n\n']
    for n in ns:
        L.append("extern const hkfsm_scene_def hkfsm_scene_" + n + ";\n")
    L.append("\nstatic const hkfsm_scene_def *const HKFSM_REGISTRY_SCENES[] = {\n")
    for n in ns:
        L.append("    &hkfsm_scene_" + n + ",\n")
    L.append("};\n")
    return "".join(L), ns


def gen_act():
    """sim/fsm/actions/act_registry_list.inc -- every `const act_vtable *const act_registry_<name>[]`
    defined in a .c anywhere under sim/fsm.  Names must be unique.  Lookup order does not matter:
    gate/dup_actions.py keeps each action type registered once.
    """
    rx = re.compile(r"^\s*const\s+act_vtable\s*\*\s*const\s+act_registry_(\w+)\s*\[\s*\]", re.M)
    found = {}
    for dirpath, dirs, files in os.walk(os.path.join(SIM, "fsm")):
        dirs.sort()
        for fn in sorted(files):
            if not fn.endswith(".c"):
                continue
            path = os.path.join(dirpath, fn)
            with open(path, "r", encoding="utf-8", errors="replace") as f:
                for n in rx.findall(f.read()):
                    if n in found:
                        sys.exit("gen_registries: act_registry_%s defined in both %s and %s" % (n, found[n], path))
                    found[n] = path
    ns = sorted(found)
    L = [BANNER]
    for n in ns:
        L.append("extern const act_vtable *const act_registry_" + n + "[]; extern const int act_registry_" + n + "_n;\n")
    L.append("\ntypedef struct { const act_vtable *const *v; const int *n; } act_reg_entry;\n")
    L.append("static const act_reg_entry ACT_REGISTRIES[] = {\n")
    for n in ns:
        L.append("    { act_registry_" + n + ", &act_registry_" + n + "_n },\n")
    L.append("};\n")
    L.append("#define ACT_REGISTRIES_N ((int)(sizeof ACT_REGISTRIES / sizeof ACT_REGISTRIES[0]))\n")
    return "".join(L), ns


def main():
    changed = []
    core_txt, core_ns = gen_core_scenes()
    fsm_txt, fsm_ns = gen_fsm_scenes()
    act_txt, act_ns = gen_act()
    for path, txt in ((os.path.join(SIM, "core", "scene_registry.inc"), core_txt),
                      (os.path.join(SIM, "fsm", "fsm_scene_registry.inc"), fsm_txt),
                      (os.path.join(SIM, "fsm", "actions", "act_registry_list.inc"), act_txt)):
        if write_if_changed(path, txt):
            changed.append(os.path.basename(path))
    sys.stderr.write("gen_registries: %d scenes, %d fsm tables, %d action registries%s\n"
                     % (len(core_ns), len(fsm_ns), len(act_ns),
                        ("  [rewrote %s]" % ", ".join(changed)) if changed else ""))


if __name__ == "__main__":
    main()
